// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loc_cert.proto

package eu.surething_project.core.grpc;

public final class LocCertProto {
  private LocCertProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_surething_project_core_LocationVerification_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eu_surething_project_core_LocationVerification_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_surething_project_core_LocationCertificate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eu_surething_project_core_LocationCertificate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016loc_cert.proto\022\031eu.surething_project.c" +
      "ore\032\031google/protobuf/any.proto\032\016loc_time" +
      ".proto\032\017signature.proto\"\300\001\n\024LocationVeri" +
      "fication\022\022\n\nverifierId\030\001 \001(\t\022\017\n\007claimId\030" +
      "\002 \001(\t\022\026\n\016endorsementIds\030\003 \003(\t\022-\n\004time\030\004 " +
      "\001(\0132\037.eu.surething_project.core.Time\022\024\n\014" +
      "evidenceType\030\005 \001(\t\022&\n\010evidence\030\006 \001(\0132\024.g" +
      "oogle.protobuf.Any\"\235\001\n\023LocationCertifica" +
      "te\022E\n\014verification\030\001 \001(\0132/.eu.surething_" +
      "project.core.LocationVerification\022?\n\021ver" +
      "ifierSignature\030\002 \001(\0132$.eu.surething_proj" +
      "ect.core.SignatureB0\n\036eu.surething_proje" +
      "ct.core.grpcB\014LocCertProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          eu.surething_project.core.grpc.LocTimeProto.getDescriptor(),
          eu.surething_project.core.grpc.SignatureProto.getDescriptor(),
        }, assigner);
    internal_static_eu_surething_project_core_LocationVerification_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_eu_surething_project_core_LocationVerification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eu_surething_project_core_LocationVerification_descriptor,
        new java.lang.String[] { "VerifierId", "ClaimId", "EndorsementIds", "Time", "EvidenceType", "Evidence", });
    internal_static_eu_surething_project_core_LocationCertificate_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_eu_surething_project_core_LocationCertificate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eu_surething_project_core_LocationCertificate_descriptor,
        new java.lang.String[] { "Verification", "VerifierSignature", });
    com.google.protobuf.AnyProto.getDescriptor();
    eu.surething_project.core.grpc.LocTimeProto.getDescriptor();
    eu.surething_project.core.grpc.SignatureProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
