// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loc_time.proto

package eu.surething_project.core.grpc;

/**
 * <pre>
 * Open Location Codes
 * reference: https://github.com/google/open-location-code/blob/1796878d947c6e281e383e69bbd0821f82db9566/java/src/main/java/com/google/openlocationcode/OpenLocationCode.java#L106
 * </pre>
 *
 * Protobuf type {@code eu.surething_project.core.OLC}
 */
public  final class OLC extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:eu.surething_project.core.OLC)
    OLCOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OLC.newBuilder() to construct.
  private OLC(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OLC() {
    southLatitude_ = 0D;
    westLongitude_ = 0D;
    northLatitude_ = 0D;
    eastLongitude_ = 0D;
    length_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OLC(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            southLatitude_ = input.readDouble();
            break;
          }
          case 17: {

            westLongitude_ = input.readDouble();
            break;
          }
          case 25: {

            northLatitude_ = input.readDouble();
            break;
          }
          case 33: {

            eastLongitude_ = input.readDouble();
            break;
          }
          case 40: {

            length_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return eu.surething_project.core.grpc.LocTimeProto.internal_static_eu_surething_project_core_OLC_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return eu.surething_project.core.grpc.LocTimeProto.internal_static_eu_surething_project_core_OLC_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            eu.surething_project.core.grpc.OLC.class, eu.surething_project.core.grpc.OLC.Builder.class);
  }

  public static final int SOUTHLATITUDE_FIELD_NUMBER = 1;
  private double southLatitude_;
  /**
   * <code>double southLatitude = 1;</code>
   */
  public double getSouthLatitude() {
    return southLatitude_;
  }

  public static final int WESTLONGITUDE_FIELD_NUMBER = 2;
  private double westLongitude_;
  /**
   * <code>double westLongitude = 2;</code>
   */
  public double getWestLongitude() {
    return westLongitude_;
  }

  public static final int NORTHLATITUDE_FIELD_NUMBER = 3;
  private double northLatitude_;
  /**
   * <code>double northLatitude = 3;</code>
   */
  public double getNorthLatitude() {
    return northLatitude_;
  }

  public static final int EASTLONGITUDE_FIELD_NUMBER = 4;
  private double eastLongitude_;
  /**
   * <code>double eastLongitude = 4;</code>
   */
  public double getEastLongitude() {
    return eastLongitude_;
  }

  public static final int LENGTH_FIELD_NUMBER = 5;
  private int length_;
  /**
   * <code>int32 length = 5;</code>
   */
  public int getLength() {
    return length_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (southLatitude_ != 0D) {
      output.writeDouble(1, southLatitude_);
    }
    if (westLongitude_ != 0D) {
      output.writeDouble(2, westLongitude_);
    }
    if (northLatitude_ != 0D) {
      output.writeDouble(3, northLatitude_);
    }
    if (eastLongitude_ != 0D) {
      output.writeDouble(4, eastLongitude_);
    }
    if (length_ != 0) {
      output.writeInt32(5, length_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (southLatitude_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, southLatitude_);
    }
    if (westLongitude_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, westLongitude_);
    }
    if (northLatitude_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, northLatitude_);
    }
    if (eastLongitude_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, eastLongitude_);
    }
    if (length_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, length_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof eu.surething_project.core.grpc.OLC)) {
      return super.equals(obj);
    }
    eu.surething_project.core.grpc.OLC other = (eu.surething_project.core.grpc.OLC) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getSouthLatitude())
        == java.lang.Double.doubleToLongBits(
            other.getSouthLatitude()));
    result = result && (
        java.lang.Double.doubleToLongBits(getWestLongitude())
        == java.lang.Double.doubleToLongBits(
            other.getWestLongitude()));
    result = result && (
        java.lang.Double.doubleToLongBits(getNorthLatitude())
        == java.lang.Double.doubleToLongBits(
            other.getNorthLatitude()));
    result = result && (
        java.lang.Double.doubleToLongBits(getEastLongitude())
        == java.lang.Double.doubleToLongBits(
            other.getEastLongitude()));
    result = result && (getLength()
        == other.getLength());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SOUTHLATITUDE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getSouthLatitude()));
    hash = (37 * hash) + WESTLONGITUDE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getWestLongitude()));
    hash = (37 * hash) + NORTHLATITUDE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getNorthLatitude()));
    hash = (37 * hash) + EASTLONGITUDE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getEastLongitude()));
    hash = (37 * hash) + LENGTH_FIELD_NUMBER;
    hash = (53 * hash) + getLength();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static eu.surething_project.core.grpc.OLC parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.surething_project.core.grpc.OLC parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.OLC parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.surething_project.core.grpc.OLC parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.OLC parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.surething_project.core.grpc.OLC parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.OLC parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.surething_project.core.grpc.OLC parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.OLC parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static eu.surething_project.core.grpc.OLC parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.OLC parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.surething_project.core.grpc.OLC parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(eu.surething_project.core.grpc.OLC prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Open Location Codes
   * reference: https://github.com/google/open-location-code/blob/1796878d947c6e281e383e69bbd0821f82db9566/java/src/main/java/com/google/openlocationcode/OpenLocationCode.java#L106
   * </pre>
   *
   * Protobuf type {@code eu.surething_project.core.OLC}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:eu.surething_project.core.OLC)
      eu.surething_project.core.grpc.OLCOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.surething_project.core.grpc.LocTimeProto.internal_static_eu_surething_project_core_OLC_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.surething_project.core.grpc.LocTimeProto.internal_static_eu_surething_project_core_OLC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.surething_project.core.grpc.OLC.class, eu.surething_project.core.grpc.OLC.Builder.class);
    }

    // Construct using eu.surething_project.core.grpc.OLC.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      southLatitude_ = 0D;

      westLongitude_ = 0D;

      northLatitude_ = 0D;

      eastLongitude_ = 0D;

      length_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return eu.surething_project.core.grpc.LocTimeProto.internal_static_eu_surething_project_core_OLC_descriptor;
    }

    @java.lang.Override
    public eu.surething_project.core.grpc.OLC getDefaultInstanceForType() {
      return eu.surething_project.core.grpc.OLC.getDefaultInstance();
    }

    @java.lang.Override
    public eu.surething_project.core.grpc.OLC build() {
      eu.surething_project.core.grpc.OLC result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public eu.surething_project.core.grpc.OLC buildPartial() {
      eu.surething_project.core.grpc.OLC result = new eu.surething_project.core.grpc.OLC(this);
      result.southLatitude_ = southLatitude_;
      result.westLongitude_ = westLongitude_;
      result.northLatitude_ = northLatitude_;
      result.eastLongitude_ = eastLongitude_;
      result.length_ = length_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof eu.surething_project.core.grpc.OLC) {
        return mergeFrom((eu.surething_project.core.grpc.OLC)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(eu.surething_project.core.grpc.OLC other) {
      if (other == eu.surething_project.core.grpc.OLC.getDefaultInstance()) return this;
      if (other.getSouthLatitude() != 0D) {
        setSouthLatitude(other.getSouthLatitude());
      }
      if (other.getWestLongitude() != 0D) {
        setWestLongitude(other.getWestLongitude());
      }
      if (other.getNorthLatitude() != 0D) {
        setNorthLatitude(other.getNorthLatitude());
      }
      if (other.getEastLongitude() != 0D) {
        setEastLongitude(other.getEastLongitude());
      }
      if (other.getLength() != 0) {
        setLength(other.getLength());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      eu.surething_project.core.grpc.OLC parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (eu.surething_project.core.grpc.OLC) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double southLatitude_ ;
    /**
     * <code>double southLatitude = 1;</code>
     */
    public double getSouthLatitude() {
      return southLatitude_;
    }
    /**
     * <code>double southLatitude = 1;</code>
     */
    public Builder setSouthLatitude(double value) {
      
      southLatitude_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double southLatitude = 1;</code>
     */
    public Builder clearSouthLatitude() {
      
      southLatitude_ = 0D;
      onChanged();
      return this;
    }

    private double westLongitude_ ;
    /**
     * <code>double westLongitude = 2;</code>
     */
    public double getWestLongitude() {
      return westLongitude_;
    }
    /**
     * <code>double westLongitude = 2;</code>
     */
    public Builder setWestLongitude(double value) {
      
      westLongitude_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double westLongitude = 2;</code>
     */
    public Builder clearWestLongitude() {
      
      westLongitude_ = 0D;
      onChanged();
      return this;
    }

    private double northLatitude_ ;
    /**
     * <code>double northLatitude = 3;</code>
     */
    public double getNorthLatitude() {
      return northLatitude_;
    }
    /**
     * <code>double northLatitude = 3;</code>
     */
    public Builder setNorthLatitude(double value) {
      
      northLatitude_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double northLatitude = 3;</code>
     */
    public Builder clearNorthLatitude() {
      
      northLatitude_ = 0D;
      onChanged();
      return this;
    }

    private double eastLongitude_ ;
    /**
     * <code>double eastLongitude = 4;</code>
     */
    public double getEastLongitude() {
      return eastLongitude_;
    }
    /**
     * <code>double eastLongitude = 4;</code>
     */
    public Builder setEastLongitude(double value) {
      
      eastLongitude_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double eastLongitude = 4;</code>
     */
    public Builder clearEastLongitude() {
      
      eastLongitude_ = 0D;
      onChanged();
      return this;
    }

    private int length_ ;
    /**
     * <code>int32 length = 5;</code>
     */
    public int getLength() {
      return length_;
    }
    /**
     * <code>int32 length = 5;</code>
     */
    public Builder setLength(int value) {
      
      length_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 length = 5;</code>
     */
    public Builder clearLength() {
      
      length_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:eu.surething_project.core.OLC)
  }

  // @@protoc_insertion_point(class_scope:eu.surething_project.core.OLC)
  private static final eu.surething_project.core.grpc.OLC DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new eu.surething_project.core.grpc.OLC();
  }

  public static eu.surething_project.core.grpc.OLC getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OLC>
      PARSER = new com.google.protobuf.AbstractParser<OLC>() {
    @java.lang.Override
    public OLC parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OLC(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OLC> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OLC> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public eu.surething_project.core.grpc.OLC getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

