// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: localized_text.proto

package eu.surething_project.core.grpc.google.type;

public interface LocalizedTextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.type.LocalizedText)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Localized string in the language corresponding to `language_code' below.
   * </pre>
   *
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <pre>
   * Localized string in the language corresponding to `language_code' below.
   * </pre>
   *
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <pre>
   * The text's BCP-47 language code, such as "en-US" or "sr-Latn".
   * For more information, see
   * http://www.unicode.org/reports/tr35/#Unicode_locale_identifier.
   * </pre>
   *
   * <code>string language_code = 2;</code>
   */
  java.lang.String getLanguageCode();
  /**
   * <pre>
   * The text's BCP-47 language code, such as "en-US" or "sr-Latn".
   * For more information, see
   * http://www.unicode.org/reports/tr35/#Unicode_locale_identifier.
   * </pre>
   *
   * <code>string language_code = 2;</code>
   */
  com.google.protobuf.ByteString
      getLanguageCodeBytes();
}
