// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loc_time.proto

package eu.surething_project.core.grpc.time;

/**
 * <pre>
 * Epoch time 
 * </pre>
 *
 * Protobuf type {@code eu.surething_project.core.EpochTime}
 */
public  final class EpochTime extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:eu.surething_project.core.EpochTime)
    EpochTimeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EpochTime.newBuilder() to construct.
  private EpochTime(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EpochTime() {
    epochId_ = "";
    timeValue_ = 0L;
    timeUnit_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EpochTime(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            epochId_ = s;
            break;
          }
          case 16: {

            timeValue_ = input.readInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            timeUnit_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return eu.surething_project.core.grpc.time.LocTimeProto.internal_static_eu_surething_project_core_EpochTime_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return eu.surething_project.core.grpc.time.LocTimeProto.internal_static_eu_surething_project_core_EpochTime_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            eu.surething_project.core.grpc.time.EpochTime.class, eu.surething_project.core.grpc.time.EpochTime.Builder.class);
  }

  public static final int EPOCHID_FIELD_NUMBER = 1;
  private volatile java.lang.Object epochId_;
  /**
   * <pre>
   * unique identifier
   * </pre>
   *
   * <code>string epochId = 1;</code>
   */
  public java.lang.String getEpochId() {
    java.lang.Object ref = epochId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      epochId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * unique identifier
   * </pre>
   *
   * <code>string epochId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getEpochIdBytes() {
    java.lang.Object ref = epochId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      epochId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMEVALUE_FIELD_NUMBER = 2;
  private long timeValue_;
  /**
   * <pre>
   * time value
   * </pre>
   *
   * <code>int64 timeValue = 2;</code>
   */
  public long getTimeValue() {
    return timeValue_;
  }

  public static final int TIMEUNIT_FIELD_NUMBER = 3;
  private volatile java.lang.Object timeUnit_;
  /**
   * <pre>
   * unit of time (e.g. s - seconds)
   * </pre>
   *
   * <code>string timeUnit = 3;</code>
   */
  public java.lang.String getTimeUnit() {
    java.lang.Object ref = timeUnit_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timeUnit_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * unit of time (e.g. s - seconds)
   * </pre>
   *
   * <code>string timeUnit = 3;</code>
   */
  public com.google.protobuf.ByteString
      getTimeUnitBytes() {
    java.lang.Object ref = timeUnit_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timeUnit_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getEpochIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, epochId_);
    }
    if (timeValue_ != 0L) {
      output.writeInt64(2, timeValue_);
    }
    if (!getTimeUnitBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, timeUnit_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getEpochIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, epochId_);
    }
    if (timeValue_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, timeValue_);
    }
    if (!getTimeUnitBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, timeUnit_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof eu.surething_project.core.grpc.time.EpochTime)) {
      return super.equals(obj);
    }
    eu.surething_project.core.grpc.time.EpochTime other = (eu.surething_project.core.grpc.time.EpochTime) obj;

    boolean result = true;
    result = result && getEpochId()
        .equals(other.getEpochId());
    result = result && (getTimeValue()
        == other.getTimeValue());
    result = result && getTimeUnit()
        .equals(other.getTimeUnit());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EPOCHID_FIELD_NUMBER;
    hash = (53 * hash) + getEpochId().hashCode();
    hash = (37 * hash) + TIMEVALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimeValue());
    hash = (37 * hash) + TIMEUNIT_FIELD_NUMBER;
    hash = (53 * hash) + getTimeUnit().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static eu.surething_project.core.grpc.time.EpochTime parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.surething_project.core.grpc.time.EpochTime parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.time.EpochTime parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.surething_project.core.grpc.time.EpochTime parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.time.EpochTime parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.surething_project.core.grpc.time.EpochTime parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.time.EpochTime parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.surething_project.core.grpc.time.EpochTime parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.time.EpochTime parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static eu.surething_project.core.grpc.time.EpochTime parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.time.EpochTime parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.surething_project.core.grpc.time.EpochTime parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(eu.surething_project.core.grpc.time.EpochTime prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Epoch time 
   * </pre>
   *
   * Protobuf type {@code eu.surething_project.core.EpochTime}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:eu.surething_project.core.EpochTime)
      eu.surething_project.core.grpc.time.EpochTimeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.surething_project.core.grpc.time.LocTimeProto.internal_static_eu_surething_project_core_EpochTime_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.surething_project.core.grpc.time.LocTimeProto.internal_static_eu_surething_project_core_EpochTime_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.surething_project.core.grpc.time.EpochTime.class, eu.surething_project.core.grpc.time.EpochTime.Builder.class);
    }

    // Construct using eu.surething_project.core.grpc.time.EpochTime.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      epochId_ = "";

      timeValue_ = 0L;

      timeUnit_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return eu.surething_project.core.grpc.time.LocTimeProto.internal_static_eu_surething_project_core_EpochTime_descriptor;
    }

    @java.lang.Override
    public eu.surething_project.core.grpc.time.EpochTime getDefaultInstanceForType() {
      return eu.surething_project.core.grpc.time.EpochTime.getDefaultInstance();
    }

    @java.lang.Override
    public eu.surething_project.core.grpc.time.EpochTime build() {
      eu.surething_project.core.grpc.time.EpochTime result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public eu.surething_project.core.grpc.time.EpochTime buildPartial() {
      eu.surething_project.core.grpc.time.EpochTime result = new eu.surething_project.core.grpc.time.EpochTime(this);
      result.epochId_ = epochId_;
      result.timeValue_ = timeValue_;
      result.timeUnit_ = timeUnit_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof eu.surething_project.core.grpc.time.EpochTime) {
        return mergeFrom((eu.surething_project.core.grpc.time.EpochTime)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(eu.surething_project.core.grpc.time.EpochTime other) {
      if (other == eu.surething_project.core.grpc.time.EpochTime.getDefaultInstance()) return this;
      if (!other.getEpochId().isEmpty()) {
        epochId_ = other.epochId_;
        onChanged();
      }
      if (other.getTimeValue() != 0L) {
        setTimeValue(other.getTimeValue());
      }
      if (!other.getTimeUnit().isEmpty()) {
        timeUnit_ = other.timeUnit_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      eu.surething_project.core.grpc.time.EpochTime parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (eu.surething_project.core.grpc.time.EpochTime) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object epochId_ = "";
    /**
     * <pre>
     * unique identifier
     * </pre>
     *
     * <code>string epochId = 1;</code>
     */
    public java.lang.String getEpochId() {
      java.lang.Object ref = epochId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        epochId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * unique identifier
     * </pre>
     *
     * <code>string epochId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEpochIdBytes() {
      java.lang.Object ref = epochId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        epochId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * unique identifier
     * </pre>
     *
     * <code>string epochId = 1;</code>
     */
    public Builder setEpochId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      epochId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unique identifier
     * </pre>
     *
     * <code>string epochId = 1;</code>
     */
    public Builder clearEpochId() {
      
      epochId_ = getDefaultInstance().getEpochId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unique identifier
     * </pre>
     *
     * <code>string epochId = 1;</code>
     */
    public Builder setEpochIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      epochId_ = value;
      onChanged();
      return this;
    }

    private long timeValue_ ;
    /**
     * <pre>
     * time value
     * </pre>
     *
     * <code>int64 timeValue = 2;</code>
     */
    public long getTimeValue() {
      return timeValue_;
    }
    /**
     * <pre>
     * time value
     * </pre>
     *
     * <code>int64 timeValue = 2;</code>
     */
    public Builder setTimeValue(long value) {
      
      timeValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * time value
     * </pre>
     *
     * <code>int64 timeValue = 2;</code>
     */
    public Builder clearTimeValue() {
      
      timeValue_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object timeUnit_ = "";
    /**
     * <pre>
     * unit of time (e.g. s - seconds)
     * </pre>
     *
     * <code>string timeUnit = 3;</code>
     */
    public java.lang.String getTimeUnit() {
      java.lang.Object ref = timeUnit_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timeUnit_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * unit of time (e.g. s - seconds)
     * </pre>
     *
     * <code>string timeUnit = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTimeUnitBytes() {
      java.lang.Object ref = timeUnit_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeUnit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * unit of time (e.g. s - seconds)
     * </pre>
     *
     * <code>string timeUnit = 3;</code>
     */
    public Builder setTimeUnit(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      timeUnit_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unit of time (e.g. s - seconds)
     * </pre>
     *
     * <code>string timeUnit = 3;</code>
     */
    public Builder clearTimeUnit() {
      
      timeUnit_ = getDefaultInstance().getTimeUnit();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unit of time (e.g. s - seconds)
     * </pre>
     *
     * <code>string timeUnit = 3;</code>
     */
    public Builder setTimeUnitBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      timeUnit_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:eu.surething_project.core.EpochTime)
  }

  // @@protoc_insertion_point(class_scope:eu.surething_project.core.EpochTime)
  private static final eu.surething_project.core.grpc.time.EpochTime DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new eu.surething_project.core.grpc.time.EpochTime();
  }

  public static eu.surething_project.core.grpc.time.EpochTime getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EpochTime>
      PARSER = new com.google.protobuf.AbstractParser<EpochTime>() {
    @java.lang.Override
    public EpochTime parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EpochTime(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EpochTime> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EpochTime> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public eu.surething_project.core.grpc.time.EpochTime getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

