// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loc_time.proto

package eu.surething_project.core.grpc.time;

public interface EpochTimeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eu.surething_project.core.EpochTime)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * unique identifier
   * </pre>
   *
   * <code>string epochId = 1;</code>
   */
  java.lang.String getEpochId();
  /**
   * <pre>
   * unique identifier
   * </pre>
   *
   * <code>string epochId = 1;</code>
   */
  com.google.protobuf.ByteString
      getEpochIdBytes();

  /**
   * <pre>
   * time value
   * </pre>
   *
   * <code>int64 timeValue = 2;</code>
   */
  long getTimeValue();

  /**
   * <pre>
   * unit of time (e.g. s - seconds)
   * </pre>
   *
   * <code>string timeUnit = 3;</code>
   */
  java.lang.String getTimeUnit();
  /**
   * <pre>
   * unit of time (e.g. s - seconds)
   * </pre>
   *
   * <code>string timeUnit = 3;</code>
   */
  com.google.protobuf.ByteString
      getTimeUnitBytes();
}
