// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loc_time.proto

package eu.surething_project.core.grpc.time;

public interface OLCOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eu.surething_project.core.OLC)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double southLatitude = 1;</code>
   */
  double getSouthLatitude();

  /**
   * <code>double westLongitude = 2;</code>
   */
  double getWestLongitude();

  /**
   * <code>double northLatitude = 3;</code>
   */
  double getNorthLatitude();

  /**
   * <code>double eastLongitude = 4;</code>
   */
  double getEastLongitude();

  /**
   * <code>int32 length = 5;</code>
   */
  int getLength();
}
