// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loc_time.proto

package eu.surething_project.core.grpc.time;

/**
 * <pre>
 * Point-of-Interest (PoI) location
 * </pre>
 *
 * Protobuf type {@code eu.surething_project.core.PoI}
 */
public  final class PoI extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:eu.surething_project.core.PoI)
    PoIOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PoI.newBuilder() to construct.
  private PoI(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PoI() {
    id_ = "";
    name_ = "";
    localizedName_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PoI(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              localizedName_ = new java.util.ArrayList<eu.surething_project.core.grpc.google.type.LocalizedText>();
              mutable_bitField0_ |= 0x00000004;
            }
            localizedName_.add(
                input.readMessage(eu.surething_project.core.grpc.google.type.LocalizedText.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        localizedName_ = java.util.Collections.unmodifiableList(localizedName_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return eu.surething_project.core.grpc.time.LocTimeProto.internal_static_eu_surething_project_core_PoI_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return eu.surething_project.core.grpc.time.LocTimeProto.internal_static_eu_surething_project_core_PoI_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            eu.surething_project.core.grpc.time.PoI.class, eu.surething_project.core.grpc.time.PoI.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <pre>
   * unique identifier
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * unique identifier
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   * name of point-of-interest
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * name of point-of-interest
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOCALIZEDNAME_FIELD_NUMBER = 3;
  private java.util.List<eu.surething_project.core.grpc.google.type.LocalizedText> localizedName_;
  /**
   * <pre>
   * name in different locales
   * </pre>
   *
   * <code>repeated .google.type.LocalizedText localizedName = 3;</code>
   */
  public java.util.List<eu.surething_project.core.grpc.google.type.LocalizedText> getLocalizedNameList() {
    return localizedName_;
  }
  /**
   * <pre>
   * name in different locales
   * </pre>
   *
   * <code>repeated .google.type.LocalizedText localizedName = 3;</code>
   */
  public java.util.List<? extends eu.surething_project.core.grpc.google.type.LocalizedTextOrBuilder> 
      getLocalizedNameOrBuilderList() {
    return localizedName_;
  }
  /**
   * <pre>
   * name in different locales
   * </pre>
   *
   * <code>repeated .google.type.LocalizedText localizedName = 3;</code>
   */
  public int getLocalizedNameCount() {
    return localizedName_.size();
  }
  /**
   * <pre>
   * name in different locales
   * </pre>
   *
   * <code>repeated .google.type.LocalizedText localizedName = 3;</code>
   */
  public eu.surething_project.core.grpc.google.type.LocalizedText getLocalizedName(int index) {
    return localizedName_.get(index);
  }
  /**
   * <pre>
   * name in different locales
   * </pre>
   *
   * <code>repeated .google.type.LocalizedText localizedName = 3;</code>
   */
  public eu.surething_project.core.grpc.google.type.LocalizedTextOrBuilder getLocalizedNameOrBuilder(
      int index) {
    return localizedName_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    for (int i = 0; i < localizedName_.size(); i++) {
      output.writeMessage(3, localizedName_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    for (int i = 0; i < localizedName_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, localizedName_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof eu.surething_project.core.grpc.time.PoI)) {
      return super.equals(obj);
    }
    eu.surething_project.core.grpc.time.PoI other = (eu.surething_project.core.grpc.time.PoI) obj;

    boolean result = true;
    result = result && getId()
        .equals(other.getId());
    result = result && getName()
        .equals(other.getName());
    result = result && getLocalizedNameList()
        .equals(other.getLocalizedNameList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (getLocalizedNameCount() > 0) {
      hash = (37 * hash) + LOCALIZEDNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLocalizedNameList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static eu.surething_project.core.grpc.time.PoI parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.surething_project.core.grpc.time.PoI parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.time.PoI parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.surething_project.core.grpc.time.PoI parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.time.PoI parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.surething_project.core.grpc.time.PoI parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.time.PoI parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.surething_project.core.grpc.time.PoI parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.time.PoI parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static eu.surething_project.core.grpc.time.PoI parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.time.PoI parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.surething_project.core.grpc.time.PoI parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(eu.surething_project.core.grpc.time.PoI prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Point-of-Interest (PoI) location
   * </pre>
   *
   * Protobuf type {@code eu.surething_project.core.PoI}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:eu.surething_project.core.PoI)
      eu.surething_project.core.grpc.time.PoIOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.surething_project.core.grpc.time.LocTimeProto.internal_static_eu_surething_project_core_PoI_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.surething_project.core.grpc.time.LocTimeProto.internal_static_eu_surething_project_core_PoI_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.surething_project.core.grpc.time.PoI.class, eu.surething_project.core.grpc.time.PoI.Builder.class);
    }

    // Construct using eu.surething_project.core.grpc.time.PoI.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getLocalizedNameFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      name_ = "";

      if (localizedNameBuilder_ == null) {
        localizedName_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        localizedNameBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return eu.surething_project.core.grpc.time.LocTimeProto.internal_static_eu_surething_project_core_PoI_descriptor;
    }

    @java.lang.Override
    public eu.surething_project.core.grpc.time.PoI getDefaultInstanceForType() {
      return eu.surething_project.core.grpc.time.PoI.getDefaultInstance();
    }

    @java.lang.Override
    public eu.surething_project.core.grpc.time.PoI build() {
      eu.surething_project.core.grpc.time.PoI result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public eu.surething_project.core.grpc.time.PoI buildPartial() {
      eu.surething_project.core.grpc.time.PoI result = new eu.surething_project.core.grpc.time.PoI(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.name_ = name_;
      if (localizedNameBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          localizedName_ = java.util.Collections.unmodifiableList(localizedName_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.localizedName_ = localizedName_;
      } else {
        result.localizedName_ = localizedNameBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof eu.surething_project.core.grpc.time.PoI) {
        return mergeFrom((eu.surething_project.core.grpc.time.PoI)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(eu.surething_project.core.grpc.time.PoI other) {
      if (other == eu.surething_project.core.grpc.time.PoI.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (localizedNameBuilder_ == null) {
        if (!other.localizedName_.isEmpty()) {
          if (localizedName_.isEmpty()) {
            localizedName_ = other.localizedName_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureLocalizedNameIsMutable();
            localizedName_.addAll(other.localizedName_);
          }
          onChanged();
        }
      } else {
        if (!other.localizedName_.isEmpty()) {
          if (localizedNameBuilder_.isEmpty()) {
            localizedNameBuilder_.dispose();
            localizedNameBuilder_ = null;
            localizedName_ = other.localizedName_;
            bitField0_ = (bitField0_ & ~0x00000004);
            localizedNameBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getLocalizedNameFieldBuilder() : null;
          } else {
            localizedNameBuilder_.addAllMessages(other.localizedName_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      eu.surething_project.core.grpc.time.PoI parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (eu.surething_project.core.grpc.time.PoI) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <pre>
     * unique identifier
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * unique identifier
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * unique identifier
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unique identifier
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unique identifier
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * name of point-of-interest
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * name of point-of-interest
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * name of point-of-interest
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * name of point-of-interest
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * name of point-of-interest
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.util.List<eu.surething_project.core.grpc.google.type.LocalizedText> localizedName_ =
      java.util.Collections.emptyList();
    private void ensureLocalizedNameIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        localizedName_ = new java.util.ArrayList<eu.surething_project.core.grpc.google.type.LocalizedText>(localizedName_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        eu.surething_project.core.grpc.google.type.LocalizedText, eu.surething_project.core.grpc.google.type.LocalizedText.Builder, eu.surething_project.core.grpc.google.type.LocalizedTextOrBuilder> localizedNameBuilder_;

    /**
     * <pre>
     * name in different locales
     * </pre>
     *
     * <code>repeated .google.type.LocalizedText localizedName = 3;</code>
     */
    public java.util.List<eu.surething_project.core.grpc.google.type.LocalizedText> getLocalizedNameList() {
      if (localizedNameBuilder_ == null) {
        return java.util.Collections.unmodifiableList(localizedName_);
      } else {
        return localizedNameBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * name in different locales
     * </pre>
     *
     * <code>repeated .google.type.LocalizedText localizedName = 3;</code>
     */
    public int getLocalizedNameCount() {
      if (localizedNameBuilder_ == null) {
        return localizedName_.size();
      } else {
        return localizedNameBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * name in different locales
     * </pre>
     *
     * <code>repeated .google.type.LocalizedText localizedName = 3;</code>
     */
    public eu.surething_project.core.grpc.google.type.LocalizedText getLocalizedName(int index) {
      if (localizedNameBuilder_ == null) {
        return localizedName_.get(index);
      } else {
        return localizedNameBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * name in different locales
     * </pre>
     *
     * <code>repeated .google.type.LocalizedText localizedName = 3;</code>
     */
    public Builder setLocalizedName(
        int index, eu.surething_project.core.grpc.google.type.LocalizedText value) {
      if (localizedNameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLocalizedNameIsMutable();
        localizedName_.set(index, value);
        onChanged();
      } else {
        localizedNameBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * name in different locales
     * </pre>
     *
     * <code>repeated .google.type.LocalizedText localizedName = 3;</code>
     */
    public Builder setLocalizedName(
        int index, eu.surething_project.core.grpc.google.type.LocalizedText.Builder builderForValue) {
      if (localizedNameBuilder_ == null) {
        ensureLocalizedNameIsMutable();
        localizedName_.set(index, builderForValue.build());
        onChanged();
      } else {
        localizedNameBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * name in different locales
     * </pre>
     *
     * <code>repeated .google.type.LocalizedText localizedName = 3;</code>
     */
    public Builder addLocalizedName(eu.surething_project.core.grpc.google.type.LocalizedText value) {
      if (localizedNameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLocalizedNameIsMutable();
        localizedName_.add(value);
        onChanged();
      } else {
        localizedNameBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * name in different locales
     * </pre>
     *
     * <code>repeated .google.type.LocalizedText localizedName = 3;</code>
     */
    public Builder addLocalizedName(
        int index, eu.surething_project.core.grpc.google.type.LocalizedText value) {
      if (localizedNameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLocalizedNameIsMutable();
        localizedName_.add(index, value);
        onChanged();
      } else {
        localizedNameBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * name in different locales
     * </pre>
     *
     * <code>repeated .google.type.LocalizedText localizedName = 3;</code>
     */
    public Builder addLocalizedName(
        eu.surething_project.core.grpc.google.type.LocalizedText.Builder builderForValue) {
      if (localizedNameBuilder_ == null) {
        ensureLocalizedNameIsMutable();
        localizedName_.add(builderForValue.build());
        onChanged();
      } else {
        localizedNameBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * name in different locales
     * </pre>
     *
     * <code>repeated .google.type.LocalizedText localizedName = 3;</code>
     */
    public Builder addLocalizedName(
        int index, eu.surething_project.core.grpc.google.type.LocalizedText.Builder builderForValue) {
      if (localizedNameBuilder_ == null) {
        ensureLocalizedNameIsMutable();
        localizedName_.add(index, builderForValue.build());
        onChanged();
      } else {
        localizedNameBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * name in different locales
     * </pre>
     *
     * <code>repeated .google.type.LocalizedText localizedName = 3;</code>
     */
    public Builder addAllLocalizedName(
        java.lang.Iterable<? extends eu.surething_project.core.grpc.google.type.LocalizedText> values) {
      if (localizedNameBuilder_ == null) {
        ensureLocalizedNameIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, localizedName_);
        onChanged();
      } else {
        localizedNameBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * name in different locales
     * </pre>
     *
     * <code>repeated .google.type.LocalizedText localizedName = 3;</code>
     */
    public Builder clearLocalizedName() {
      if (localizedNameBuilder_ == null) {
        localizedName_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        localizedNameBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * name in different locales
     * </pre>
     *
     * <code>repeated .google.type.LocalizedText localizedName = 3;</code>
     */
    public Builder removeLocalizedName(int index) {
      if (localizedNameBuilder_ == null) {
        ensureLocalizedNameIsMutable();
        localizedName_.remove(index);
        onChanged();
      } else {
        localizedNameBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * name in different locales
     * </pre>
     *
     * <code>repeated .google.type.LocalizedText localizedName = 3;</code>
     */
    public eu.surething_project.core.grpc.google.type.LocalizedText.Builder getLocalizedNameBuilder(
        int index) {
      return getLocalizedNameFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * name in different locales
     * </pre>
     *
     * <code>repeated .google.type.LocalizedText localizedName = 3;</code>
     */
    public eu.surething_project.core.grpc.google.type.LocalizedTextOrBuilder getLocalizedNameOrBuilder(
        int index) {
      if (localizedNameBuilder_ == null) {
        return localizedName_.get(index);  } else {
        return localizedNameBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * name in different locales
     * </pre>
     *
     * <code>repeated .google.type.LocalizedText localizedName = 3;</code>
     */
    public java.util.List<? extends eu.surething_project.core.grpc.google.type.LocalizedTextOrBuilder> 
         getLocalizedNameOrBuilderList() {
      if (localizedNameBuilder_ != null) {
        return localizedNameBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(localizedName_);
      }
    }
    /**
     * <pre>
     * name in different locales
     * </pre>
     *
     * <code>repeated .google.type.LocalizedText localizedName = 3;</code>
     */
    public eu.surething_project.core.grpc.google.type.LocalizedText.Builder addLocalizedNameBuilder() {
      return getLocalizedNameFieldBuilder().addBuilder(
          eu.surething_project.core.grpc.google.type.LocalizedText.getDefaultInstance());
    }
    /**
     * <pre>
     * name in different locales
     * </pre>
     *
     * <code>repeated .google.type.LocalizedText localizedName = 3;</code>
     */
    public eu.surething_project.core.grpc.google.type.LocalizedText.Builder addLocalizedNameBuilder(
        int index) {
      return getLocalizedNameFieldBuilder().addBuilder(
          index, eu.surething_project.core.grpc.google.type.LocalizedText.getDefaultInstance());
    }
    /**
     * <pre>
     * name in different locales
     * </pre>
     *
     * <code>repeated .google.type.LocalizedText localizedName = 3;</code>
     */
    public java.util.List<eu.surething_project.core.grpc.google.type.LocalizedText.Builder> 
         getLocalizedNameBuilderList() {
      return getLocalizedNameFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        eu.surething_project.core.grpc.google.type.LocalizedText, eu.surething_project.core.grpc.google.type.LocalizedText.Builder, eu.surething_project.core.grpc.google.type.LocalizedTextOrBuilder> 
        getLocalizedNameFieldBuilder() {
      if (localizedNameBuilder_ == null) {
        localizedNameBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            eu.surething_project.core.grpc.google.type.LocalizedText, eu.surething_project.core.grpc.google.type.LocalizedText.Builder, eu.surething_project.core.grpc.google.type.LocalizedTextOrBuilder>(
                localizedName_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        localizedName_ = null;
      }
      return localizedNameBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:eu.surething_project.core.PoI)
  }

  // @@protoc_insertion_point(class_scope:eu.surething_project.core.PoI)
  private static final eu.surething_project.core.grpc.time.PoI DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new eu.surething_project.core.grpc.time.PoI();
  }

  public static eu.surething_project.core.grpc.time.PoI getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PoI>
      PARSER = new com.google.protobuf.AbstractParser<PoI>() {
    @java.lang.Override
    public PoI parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PoI(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PoI> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PoI> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public eu.surething_project.core.grpc.time.PoI getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

