// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loc_time.proto

package eu.surething_project.core.grpc.time;

/**
 * <pre>
 * Point-of-Interest proximity location
 * </pre>
 *
 * Protobuf type {@code eu.surething_project.core.PoIProximity}
 */
public  final class PoIProximity extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:eu.surething_project.core.PoIProximity)
    PoIProximityOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PoIProximity.newBuilder() to construct.
  private PoIProximity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PoIProximity() {
    poiId_ = "";
    distanceValue_ = 0L;
    distanceUnit_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PoIProximity(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            poiId_ = s;
            break;
          }
          case 16: {

            distanceValue_ = input.readUInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            distanceUnit_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return eu.surething_project.core.grpc.time.LocTimeProto.internal_static_eu_surething_project_core_PoIProximity_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return eu.surething_project.core.grpc.time.LocTimeProto.internal_static_eu_surething_project_core_PoIProximity_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            eu.surething_project.core.grpc.time.PoIProximity.class, eu.surething_project.core.grpc.time.PoIProximity.Builder.class);
  }

  public static final int POIID_FIELD_NUMBER = 1;
  private volatile java.lang.Object poiId_;
  /**
   * <pre>
   * unique identifier for point-of-interest
   * </pre>
   *
   * <code>string poiId = 1;</code>
   */
  public java.lang.String getPoiId() {
    java.lang.Object ref = poiId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      poiId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * unique identifier for point-of-interest
   * </pre>
   *
   * <code>string poiId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getPoiIdBytes() {
    java.lang.Object ref = poiId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      poiId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISTANCEVALUE_FIELD_NUMBER = 2;
  private long distanceValue_;
  /**
   * <pre>
   * distance to PoI, &gt;= 0
   * </pre>
   *
   * <code>uint64 distanceValue = 2;</code>
   */
  public long getDistanceValue() {
    return distanceValue_;
  }

  public static final int DISTANCEUNIT_FIELD_NUMBER = 3;
  private volatile java.lang.Object distanceUnit_;
  /**
   * <pre>
   * unit of distance (e.g. cm)
   * </pre>
   *
   * <code>string distanceUnit = 3;</code>
   */
  public java.lang.String getDistanceUnit() {
    java.lang.Object ref = distanceUnit_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      distanceUnit_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * unit of distance (e.g. cm)
   * </pre>
   *
   * <code>string distanceUnit = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDistanceUnitBytes() {
    java.lang.Object ref = distanceUnit_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      distanceUnit_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getPoiIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, poiId_);
    }
    if (distanceValue_ != 0L) {
      output.writeUInt64(2, distanceValue_);
    }
    if (!getDistanceUnitBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, distanceUnit_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getPoiIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, poiId_);
    }
    if (distanceValue_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, distanceValue_);
    }
    if (!getDistanceUnitBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, distanceUnit_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof eu.surething_project.core.grpc.time.PoIProximity)) {
      return super.equals(obj);
    }
    eu.surething_project.core.grpc.time.PoIProximity other = (eu.surething_project.core.grpc.time.PoIProximity) obj;

    boolean result = true;
    result = result && getPoiId()
        .equals(other.getPoiId());
    result = result && (getDistanceValue()
        == other.getDistanceValue());
    result = result && getDistanceUnit()
        .equals(other.getDistanceUnit());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + POIID_FIELD_NUMBER;
    hash = (53 * hash) + getPoiId().hashCode();
    hash = (37 * hash) + DISTANCEVALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDistanceValue());
    hash = (37 * hash) + DISTANCEUNIT_FIELD_NUMBER;
    hash = (53 * hash) + getDistanceUnit().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static eu.surething_project.core.grpc.time.PoIProximity parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.surething_project.core.grpc.time.PoIProximity parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.time.PoIProximity parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.surething_project.core.grpc.time.PoIProximity parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.time.PoIProximity parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.surething_project.core.grpc.time.PoIProximity parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.time.PoIProximity parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.surething_project.core.grpc.time.PoIProximity parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.time.PoIProximity parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static eu.surething_project.core.grpc.time.PoIProximity parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.time.PoIProximity parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.surething_project.core.grpc.time.PoIProximity parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(eu.surething_project.core.grpc.time.PoIProximity prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Point-of-Interest proximity location
   * </pre>
   *
   * Protobuf type {@code eu.surething_project.core.PoIProximity}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:eu.surething_project.core.PoIProximity)
      eu.surething_project.core.grpc.time.PoIProximityOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.surething_project.core.grpc.time.LocTimeProto.internal_static_eu_surething_project_core_PoIProximity_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.surething_project.core.grpc.time.LocTimeProto.internal_static_eu_surething_project_core_PoIProximity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.surething_project.core.grpc.time.PoIProximity.class, eu.surething_project.core.grpc.time.PoIProximity.Builder.class);
    }

    // Construct using eu.surething_project.core.grpc.time.PoIProximity.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      poiId_ = "";

      distanceValue_ = 0L;

      distanceUnit_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return eu.surething_project.core.grpc.time.LocTimeProto.internal_static_eu_surething_project_core_PoIProximity_descriptor;
    }

    @java.lang.Override
    public eu.surething_project.core.grpc.time.PoIProximity getDefaultInstanceForType() {
      return eu.surething_project.core.grpc.time.PoIProximity.getDefaultInstance();
    }

    @java.lang.Override
    public eu.surething_project.core.grpc.time.PoIProximity build() {
      eu.surething_project.core.grpc.time.PoIProximity result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public eu.surething_project.core.grpc.time.PoIProximity buildPartial() {
      eu.surething_project.core.grpc.time.PoIProximity result = new eu.surething_project.core.grpc.time.PoIProximity(this);
      result.poiId_ = poiId_;
      result.distanceValue_ = distanceValue_;
      result.distanceUnit_ = distanceUnit_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof eu.surething_project.core.grpc.time.PoIProximity) {
        return mergeFrom((eu.surething_project.core.grpc.time.PoIProximity)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(eu.surething_project.core.grpc.time.PoIProximity other) {
      if (other == eu.surething_project.core.grpc.time.PoIProximity.getDefaultInstance()) return this;
      if (!other.getPoiId().isEmpty()) {
        poiId_ = other.poiId_;
        onChanged();
      }
      if (other.getDistanceValue() != 0L) {
        setDistanceValue(other.getDistanceValue());
      }
      if (!other.getDistanceUnit().isEmpty()) {
        distanceUnit_ = other.distanceUnit_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      eu.surething_project.core.grpc.time.PoIProximity parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (eu.surething_project.core.grpc.time.PoIProximity) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object poiId_ = "";
    /**
     * <pre>
     * unique identifier for point-of-interest
     * </pre>
     *
     * <code>string poiId = 1;</code>
     */
    public java.lang.String getPoiId() {
      java.lang.Object ref = poiId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        poiId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * unique identifier for point-of-interest
     * </pre>
     *
     * <code>string poiId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPoiIdBytes() {
      java.lang.Object ref = poiId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        poiId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * unique identifier for point-of-interest
     * </pre>
     *
     * <code>string poiId = 1;</code>
     */
    public Builder setPoiId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      poiId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unique identifier for point-of-interest
     * </pre>
     *
     * <code>string poiId = 1;</code>
     */
    public Builder clearPoiId() {
      
      poiId_ = getDefaultInstance().getPoiId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unique identifier for point-of-interest
     * </pre>
     *
     * <code>string poiId = 1;</code>
     */
    public Builder setPoiIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      poiId_ = value;
      onChanged();
      return this;
    }

    private long distanceValue_ ;
    /**
     * <pre>
     * distance to PoI, &gt;= 0
     * </pre>
     *
     * <code>uint64 distanceValue = 2;</code>
     */
    public long getDistanceValue() {
      return distanceValue_;
    }
    /**
     * <pre>
     * distance to PoI, &gt;= 0
     * </pre>
     *
     * <code>uint64 distanceValue = 2;</code>
     */
    public Builder setDistanceValue(long value) {
      
      distanceValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * distance to PoI, &gt;= 0
     * </pre>
     *
     * <code>uint64 distanceValue = 2;</code>
     */
    public Builder clearDistanceValue() {
      
      distanceValue_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object distanceUnit_ = "";
    /**
     * <pre>
     * unit of distance (e.g. cm)
     * </pre>
     *
     * <code>string distanceUnit = 3;</code>
     */
    public java.lang.String getDistanceUnit() {
      java.lang.Object ref = distanceUnit_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        distanceUnit_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * unit of distance (e.g. cm)
     * </pre>
     *
     * <code>string distanceUnit = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDistanceUnitBytes() {
      java.lang.Object ref = distanceUnit_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        distanceUnit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * unit of distance (e.g. cm)
     * </pre>
     *
     * <code>string distanceUnit = 3;</code>
     */
    public Builder setDistanceUnit(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      distanceUnit_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unit of distance (e.g. cm)
     * </pre>
     *
     * <code>string distanceUnit = 3;</code>
     */
    public Builder clearDistanceUnit() {
      
      distanceUnit_ = getDefaultInstance().getDistanceUnit();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unit of distance (e.g. cm)
     * </pre>
     *
     * <code>string distanceUnit = 3;</code>
     */
    public Builder setDistanceUnitBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      distanceUnit_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:eu.surething_project.core.PoIProximity)
  }

  // @@protoc_insertion_point(class_scope:eu.surething_project.core.PoIProximity)
  private static final eu.surething_project.core.grpc.time.PoIProximity DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new eu.surething_project.core.grpc.time.PoIProximity();
  }

  public static eu.surething_project.core.grpc.time.PoIProximity getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PoIProximity>
      PARSER = new com.google.protobuf.AbstractParser<PoIProximity>() {
    @java.lang.Override
    public PoIProximity parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PoIProximity(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PoIProximity> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PoIProximity> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public eu.surething_project.core.grpc.time.PoIProximity getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

