// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loc_time.proto

package eu.surething_project.core.grpc.time;

/**
 * <pre>
 * Time schemas - alternatives
 * </pre>
 *
 * Protobuf type {@code eu.surething_project.core.Time}
 */
public  final class Time extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:eu.surething_project.core.Time)
    TimeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Time.newBuilder() to construct.
  private Time(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Time() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Time(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (timeCase_ == 1) {
              subBuilder = ((com.google.protobuf.Timestamp) time_).toBuilder();
            }
            time_ =
                input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.google.protobuf.Timestamp) time_);
              time_ = subBuilder.buildPartial();
            }
            timeCase_ = 1;
            break;
          }
          case 18: {
            eu.surething_project.core.grpc.time.TimeInterval.Builder subBuilder = null;
            if (timeCase_ == 2) {
              subBuilder = ((eu.surething_project.core.grpc.time.TimeInterval) time_).toBuilder();
            }
            time_ =
                input.readMessage(eu.surething_project.core.grpc.time.TimeInterval.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((eu.surething_project.core.grpc.time.TimeInterval) time_);
              time_ = subBuilder.buildPartial();
            }
            timeCase_ = 2;
            break;
          }
          case 26: {
            eu.surething_project.core.grpc.time.EpochTime.Builder subBuilder = null;
            if (timeCase_ == 3) {
              subBuilder = ((eu.surething_project.core.grpc.time.EpochTime) time_).toBuilder();
            }
            time_ =
                input.readMessage(eu.surething_project.core.grpc.time.EpochTime.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((eu.surething_project.core.grpc.time.EpochTime) time_);
              time_ = subBuilder.buildPartial();
            }
            timeCase_ = 3;
            break;
          }
          case 34: {
            com.google.protobuf.Empty.Builder subBuilder = null;
            if (timeCase_ == 4) {
              subBuilder = ((com.google.protobuf.Empty) time_).toBuilder();
            }
            time_ =
                input.readMessage(com.google.protobuf.Empty.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.google.protobuf.Empty) time_);
              time_ = subBuilder.buildPartial();
            }
            timeCase_ = 4;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return eu.surething_project.core.grpc.time.LocTimeProto.internal_static_eu_surething_project_core_Time_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return eu.surething_project.core.grpc.time.LocTimeProto.internal_static_eu_surething_project_core_Time_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            eu.surething_project.core.grpc.time.Time.class, eu.surething_project.core.grpc.time.Time.Builder.class);
  }

  private int timeCase_ = 0;
  private java.lang.Object time_;
  public enum TimeCase
      implements com.google.protobuf.Internal.EnumLite {
    TIMESTAMP(1),
    INTERVAL(2),
    RELATIVETOEPOCH(3),
    EMPTY(4),
    TIME_NOT_SET(0);
    private final int value;
    private TimeCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TimeCase valueOf(int value) {
      return forNumber(value);
    }

    public static TimeCase forNumber(int value) {
      switch (value) {
        case 1: return TIMESTAMP;
        case 2: return INTERVAL;
        case 3: return RELATIVETOEPOCH;
        case 4: return EMPTY;
        case 0: return TIME_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public TimeCase
  getTimeCase() {
    return TimeCase.forNumber(
        timeCase_);
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 1;
  /**
   * <pre>
   * timestamp
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 1;</code>
   */
  public boolean hasTimestamp() {
    return timeCase_ == 1;
  }
  /**
   * <pre>
   * timestamp
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 1;</code>
   */
  public com.google.protobuf.Timestamp getTimestamp() {
    if (timeCase_ == 1) {
       return (com.google.protobuf.Timestamp) time_;
    }
    return com.google.protobuf.Timestamp.getDefaultInstance();
  }
  /**
   * <pre>
   * timestamp
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 1;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
    if (timeCase_ == 1) {
       return (com.google.protobuf.Timestamp) time_;
    }
    return com.google.protobuf.Timestamp.getDefaultInstance();
  }

  public static final int INTERVAL_FIELD_NUMBER = 2;
  /**
   * <pre>
   * interval defined by two timestamps
   * </pre>
   *
   * <code>.eu.surething_project.core.TimeInterval interval = 2;</code>
   */
  public boolean hasInterval() {
    return timeCase_ == 2;
  }
  /**
   * <pre>
   * interval defined by two timestamps
   * </pre>
   *
   * <code>.eu.surething_project.core.TimeInterval interval = 2;</code>
   */
  public eu.surething_project.core.grpc.time.TimeInterval getInterval() {
    if (timeCase_ == 2) {
       return (eu.surething_project.core.grpc.time.TimeInterval) time_;
    }
    return eu.surething_project.core.grpc.time.TimeInterval.getDefaultInstance();
  }
  /**
   * <pre>
   * interval defined by two timestamps
   * </pre>
   *
   * <code>.eu.surething_project.core.TimeInterval interval = 2;</code>
   */
  public eu.surething_project.core.grpc.time.TimeIntervalOrBuilder getIntervalOrBuilder() {
    if (timeCase_ == 2) {
       return (eu.surething_project.core.grpc.time.TimeInterval) time_;
    }
    return eu.surething_project.core.grpc.time.TimeInterval.getDefaultInstance();
  }

  public static final int RELATIVETOEPOCH_FIELD_NUMBER = 3;
  /**
   * <pre>
   * time relative to epoch
   * </pre>
   *
   * <code>.eu.surething_project.core.EpochTime relativeToEpoch = 3;</code>
   */
  public boolean hasRelativeToEpoch() {
    return timeCase_ == 3;
  }
  /**
   * <pre>
   * time relative to epoch
   * </pre>
   *
   * <code>.eu.surething_project.core.EpochTime relativeToEpoch = 3;</code>
   */
  public eu.surething_project.core.grpc.time.EpochTime getRelativeToEpoch() {
    if (timeCase_ == 3) {
       return (eu.surething_project.core.grpc.time.EpochTime) time_;
    }
    return eu.surething_project.core.grpc.time.EpochTime.getDefaultInstance();
  }
  /**
   * <pre>
   * time relative to epoch
   * </pre>
   *
   * <code>.eu.surething_project.core.EpochTime relativeToEpoch = 3;</code>
   */
  public eu.surething_project.core.grpc.time.EpochTimeOrBuilder getRelativeToEpochOrBuilder() {
    if (timeCase_ == 3) {
       return (eu.surething_project.core.grpc.time.EpochTime) time_;
    }
    return eu.surething_project.core.grpc.time.EpochTime.getDefaultInstance();
  }

  public static final int EMPTY_FIELD_NUMBER = 4;
  /**
   * <pre>
   * use when we do no have time information
   * </pre>
   *
   * <code>.google.protobuf.Empty empty = 4;</code>
   */
  public boolean hasEmpty() {
    return timeCase_ == 4;
  }
  /**
   * <pre>
   * use when we do no have time information
   * </pre>
   *
   * <code>.google.protobuf.Empty empty = 4;</code>
   */
  public com.google.protobuf.Empty getEmpty() {
    if (timeCase_ == 4) {
       return (com.google.protobuf.Empty) time_;
    }
    return com.google.protobuf.Empty.getDefaultInstance();
  }
  /**
   * <pre>
   * use when we do no have time information
   * </pre>
   *
   * <code>.google.protobuf.Empty empty = 4;</code>
   */
  public com.google.protobuf.EmptyOrBuilder getEmptyOrBuilder() {
    if (timeCase_ == 4) {
       return (com.google.protobuf.Empty) time_;
    }
    return com.google.protobuf.Empty.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (timeCase_ == 1) {
      output.writeMessage(1, (com.google.protobuf.Timestamp) time_);
    }
    if (timeCase_ == 2) {
      output.writeMessage(2, (eu.surething_project.core.grpc.time.TimeInterval) time_);
    }
    if (timeCase_ == 3) {
      output.writeMessage(3, (eu.surething_project.core.grpc.time.EpochTime) time_);
    }
    if (timeCase_ == 4) {
      output.writeMessage(4, (com.google.protobuf.Empty) time_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (timeCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.google.protobuf.Timestamp) time_);
    }
    if (timeCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (eu.surething_project.core.grpc.time.TimeInterval) time_);
    }
    if (timeCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (eu.surething_project.core.grpc.time.EpochTime) time_);
    }
    if (timeCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.google.protobuf.Empty) time_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof eu.surething_project.core.grpc.time.Time)) {
      return super.equals(obj);
    }
    eu.surething_project.core.grpc.time.Time other = (eu.surething_project.core.grpc.time.Time) obj;

    boolean result = true;
    result = result && getTimeCase().equals(
        other.getTimeCase());
    if (!result) return false;
    switch (timeCase_) {
      case 1:
        result = result && getTimestamp()
            .equals(other.getTimestamp());
        break;
      case 2:
        result = result && getInterval()
            .equals(other.getInterval());
        break;
      case 3:
        result = result && getRelativeToEpoch()
            .equals(other.getRelativeToEpoch());
        break;
      case 4:
        result = result && getEmpty()
            .equals(other.getEmpty());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (timeCase_) {
      case 1:
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp().hashCode();
        break;
      case 2:
        hash = (37 * hash) + INTERVAL_FIELD_NUMBER;
        hash = (53 * hash) + getInterval().hashCode();
        break;
      case 3:
        hash = (37 * hash) + RELATIVETOEPOCH_FIELD_NUMBER;
        hash = (53 * hash) + getRelativeToEpoch().hashCode();
        break;
      case 4:
        hash = (37 * hash) + EMPTY_FIELD_NUMBER;
        hash = (53 * hash) + getEmpty().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static eu.surething_project.core.grpc.time.Time parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.surething_project.core.grpc.time.Time parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.time.Time parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.surething_project.core.grpc.time.Time parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.time.Time parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.surething_project.core.grpc.time.Time parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.time.Time parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.surething_project.core.grpc.time.Time parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.time.Time parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static eu.surething_project.core.grpc.time.Time parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.time.Time parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.surething_project.core.grpc.time.Time parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(eu.surething_project.core.grpc.time.Time prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Time schemas - alternatives
   * </pre>
   *
   * Protobuf type {@code eu.surething_project.core.Time}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:eu.surething_project.core.Time)
      eu.surething_project.core.grpc.time.TimeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.surething_project.core.grpc.time.LocTimeProto.internal_static_eu_surething_project_core_Time_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.surething_project.core.grpc.time.LocTimeProto.internal_static_eu_surething_project_core_Time_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.surething_project.core.grpc.time.Time.class, eu.surething_project.core.grpc.time.Time.Builder.class);
    }

    // Construct using eu.surething_project.core.grpc.time.Time.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      timeCase_ = 0;
      time_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return eu.surething_project.core.grpc.time.LocTimeProto.internal_static_eu_surething_project_core_Time_descriptor;
    }

    @java.lang.Override
    public eu.surething_project.core.grpc.time.Time getDefaultInstanceForType() {
      return eu.surething_project.core.grpc.time.Time.getDefaultInstance();
    }

    @java.lang.Override
    public eu.surething_project.core.grpc.time.Time build() {
      eu.surething_project.core.grpc.time.Time result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public eu.surething_project.core.grpc.time.Time buildPartial() {
      eu.surething_project.core.grpc.time.Time result = new eu.surething_project.core.grpc.time.Time(this);
      if (timeCase_ == 1) {
        if (timestampBuilder_ == null) {
          result.time_ = time_;
        } else {
          result.time_ = timestampBuilder_.build();
        }
      }
      if (timeCase_ == 2) {
        if (intervalBuilder_ == null) {
          result.time_ = time_;
        } else {
          result.time_ = intervalBuilder_.build();
        }
      }
      if (timeCase_ == 3) {
        if (relativeToEpochBuilder_ == null) {
          result.time_ = time_;
        } else {
          result.time_ = relativeToEpochBuilder_.build();
        }
      }
      if (timeCase_ == 4) {
        if (emptyBuilder_ == null) {
          result.time_ = time_;
        } else {
          result.time_ = emptyBuilder_.build();
        }
      }
      result.timeCase_ = timeCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof eu.surething_project.core.grpc.time.Time) {
        return mergeFrom((eu.surething_project.core.grpc.time.Time)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(eu.surething_project.core.grpc.time.Time other) {
      if (other == eu.surething_project.core.grpc.time.Time.getDefaultInstance()) return this;
      switch (other.getTimeCase()) {
        case TIMESTAMP: {
          mergeTimestamp(other.getTimestamp());
          break;
        }
        case INTERVAL: {
          mergeInterval(other.getInterval());
          break;
        }
        case RELATIVETOEPOCH: {
          mergeRelativeToEpoch(other.getRelativeToEpoch());
          break;
        }
        case EMPTY: {
          mergeEmpty(other.getEmpty());
          break;
        }
        case TIME_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      eu.surething_project.core.grpc.time.Time parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (eu.surething_project.core.grpc.time.Time) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int timeCase_ = 0;
    private java.lang.Object time_;
    public TimeCase
        getTimeCase() {
      return TimeCase.forNumber(
          timeCase_);
    }

    public Builder clearTime() {
      timeCase_ = 0;
      time_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
    /**
     * <pre>
     * timestamp
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    public boolean hasTimestamp() {
      return timeCase_ == 1;
    }
    /**
     * <pre>
     * timestamp
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      if (timestampBuilder_ == null) {
        if (timeCase_ == 1) {
          return (com.google.protobuf.Timestamp) time_;
        }
        return com.google.protobuf.Timestamp.getDefaultInstance();
      } else {
        if (timeCase_ == 1) {
          return timestampBuilder_.getMessage();
        }
        return com.google.protobuf.Timestamp.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * timestamp
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    public Builder setTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        time_ = value;
        onChanged();
      } else {
        timestampBuilder_.setMessage(value);
      }
      timeCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * timestamp
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    public Builder setTimestamp(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        time_ = builderForValue.build();
        onChanged();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }
      timeCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * timestamp
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (timeCase_ == 1 &&
            time_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          time_ = com.google.protobuf.Timestamp.newBuilder((com.google.protobuf.Timestamp) time_)
              .mergeFrom(value).buildPartial();
        } else {
          time_ = value;
        }
        onChanged();
      } else {
        if (timeCase_ == 1) {
          timestampBuilder_.mergeFrom(value);
        }
        timestampBuilder_.setMessage(value);
      }
      timeCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * timestamp
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    public Builder clearTimestamp() {
      if (timestampBuilder_ == null) {
        if (timeCase_ == 1) {
          timeCase_ = 0;
          time_ = null;
          onChanged();
        }
      } else {
        if (timeCase_ == 1) {
          timeCase_ = 0;
          time_ = null;
        }
        timestampBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * timestamp
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
      return getTimestampFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * timestamp
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      if ((timeCase_ == 1) && (timestampBuilder_ != null)) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        if (timeCase_ == 1) {
          return (com.google.protobuf.Timestamp) time_;
        }
        return com.google.protobuf.Timestamp.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * timestamp
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        if (!(timeCase_ == 1)) {
          time_ = com.google.protobuf.Timestamp.getDefaultInstance();
        }
        timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                (com.google.protobuf.Timestamp) time_,
                getParentForChildren(),
                isClean());
        time_ = null;
      }
      timeCase_ = 1;
      onChanged();;
      return timestampBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        eu.surething_project.core.grpc.time.TimeInterval, eu.surething_project.core.grpc.time.TimeInterval.Builder, eu.surething_project.core.grpc.time.TimeIntervalOrBuilder> intervalBuilder_;
    /**
     * <pre>
     * interval defined by two timestamps
     * </pre>
     *
     * <code>.eu.surething_project.core.TimeInterval interval = 2;</code>
     */
    public boolean hasInterval() {
      return timeCase_ == 2;
    }
    /**
     * <pre>
     * interval defined by two timestamps
     * </pre>
     *
     * <code>.eu.surething_project.core.TimeInterval interval = 2;</code>
     */
    public eu.surething_project.core.grpc.time.TimeInterval getInterval() {
      if (intervalBuilder_ == null) {
        if (timeCase_ == 2) {
          return (eu.surething_project.core.grpc.time.TimeInterval) time_;
        }
        return eu.surething_project.core.grpc.time.TimeInterval.getDefaultInstance();
      } else {
        if (timeCase_ == 2) {
          return intervalBuilder_.getMessage();
        }
        return eu.surething_project.core.grpc.time.TimeInterval.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * interval defined by two timestamps
     * </pre>
     *
     * <code>.eu.surething_project.core.TimeInterval interval = 2;</code>
     */
    public Builder setInterval(eu.surething_project.core.grpc.time.TimeInterval value) {
      if (intervalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        time_ = value;
        onChanged();
      } else {
        intervalBuilder_.setMessage(value);
      }
      timeCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * interval defined by two timestamps
     * </pre>
     *
     * <code>.eu.surething_project.core.TimeInterval interval = 2;</code>
     */
    public Builder setInterval(
        eu.surething_project.core.grpc.time.TimeInterval.Builder builderForValue) {
      if (intervalBuilder_ == null) {
        time_ = builderForValue.build();
        onChanged();
      } else {
        intervalBuilder_.setMessage(builderForValue.build());
      }
      timeCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * interval defined by two timestamps
     * </pre>
     *
     * <code>.eu.surething_project.core.TimeInterval interval = 2;</code>
     */
    public Builder mergeInterval(eu.surething_project.core.grpc.time.TimeInterval value) {
      if (intervalBuilder_ == null) {
        if (timeCase_ == 2 &&
            time_ != eu.surething_project.core.grpc.time.TimeInterval.getDefaultInstance()) {
          time_ = eu.surething_project.core.grpc.time.TimeInterval.newBuilder((eu.surething_project.core.grpc.time.TimeInterval) time_)
              .mergeFrom(value).buildPartial();
        } else {
          time_ = value;
        }
        onChanged();
      } else {
        if (timeCase_ == 2) {
          intervalBuilder_.mergeFrom(value);
        }
        intervalBuilder_.setMessage(value);
      }
      timeCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * interval defined by two timestamps
     * </pre>
     *
     * <code>.eu.surething_project.core.TimeInterval interval = 2;</code>
     */
    public Builder clearInterval() {
      if (intervalBuilder_ == null) {
        if (timeCase_ == 2) {
          timeCase_ = 0;
          time_ = null;
          onChanged();
        }
      } else {
        if (timeCase_ == 2) {
          timeCase_ = 0;
          time_ = null;
        }
        intervalBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * interval defined by two timestamps
     * </pre>
     *
     * <code>.eu.surething_project.core.TimeInterval interval = 2;</code>
     */
    public eu.surething_project.core.grpc.time.TimeInterval.Builder getIntervalBuilder() {
      return getIntervalFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * interval defined by two timestamps
     * </pre>
     *
     * <code>.eu.surething_project.core.TimeInterval interval = 2;</code>
     */
    public eu.surething_project.core.grpc.time.TimeIntervalOrBuilder getIntervalOrBuilder() {
      if ((timeCase_ == 2) && (intervalBuilder_ != null)) {
        return intervalBuilder_.getMessageOrBuilder();
      } else {
        if (timeCase_ == 2) {
          return (eu.surething_project.core.grpc.time.TimeInterval) time_;
        }
        return eu.surething_project.core.grpc.time.TimeInterval.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * interval defined by two timestamps
     * </pre>
     *
     * <code>.eu.surething_project.core.TimeInterval interval = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        eu.surething_project.core.grpc.time.TimeInterval, eu.surething_project.core.grpc.time.TimeInterval.Builder, eu.surething_project.core.grpc.time.TimeIntervalOrBuilder> 
        getIntervalFieldBuilder() {
      if (intervalBuilder_ == null) {
        if (!(timeCase_ == 2)) {
          time_ = eu.surething_project.core.grpc.time.TimeInterval.getDefaultInstance();
        }
        intervalBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            eu.surething_project.core.grpc.time.TimeInterval, eu.surething_project.core.grpc.time.TimeInterval.Builder, eu.surething_project.core.grpc.time.TimeIntervalOrBuilder>(
                (eu.surething_project.core.grpc.time.TimeInterval) time_,
                getParentForChildren(),
                isClean());
        time_ = null;
      }
      timeCase_ = 2;
      onChanged();;
      return intervalBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        eu.surething_project.core.grpc.time.EpochTime, eu.surething_project.core.grpc.time.EpochTime.Builder, eu.surething_project.core.grpc.time.EpochTimeOrBuilder> relativeToEpochBuilder_;
    /**
     * <pre>
     * time relative to epoch
     * </pre>
     *
     * <code>.eu.surething_project.core.EpochTime relativeToEpoch = 3;</code>
     */
    public boolean hasRelativeToEpoch() {
      return timeCase_ == 3;
    }
    /**
     * <pre>
     * time relative to epoch
     * </pre>
     *
     * <code>.eu.surething_project.core.EpochTime relativeToEpoch = 3;</code>
     */
    public eu.surething_project.core.grpc.time.EpochTime getRelativeToEpoch() {
      if (relativeToEpochBuilder_ == null) {
        if (timeCase_ == 3) {
          return (eu.surething_project.core.grpc.time.EpochTime) time_;
        }
        return eu.surething_project.core.grpc.time.EpochTime.getDefaultInstance();
      } else {
        if (timeCase_ == 3) {
          return relativeToEpochBuilder_.getMessage();
        }
        return eu.surething_project.core.grpc.time.EpochTime.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * time relative to epoch
     * </pre>
     *
     * <code>.eu.surething_project.core.EpochTime relativeToEpoch = 3;</code>
     */
    public Builder setRelativeToEpoch(eu.surething_project.core.grpc.time.EpochTime value) {
      if (relativeToEpochBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        time_ = value;
        onChanged();
      } else {
        relativeToEpochBuilder_.setMessage(value);
      }
      timeCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * time relative to epoch
     * </pre>
     *
     * <code>.eu.surething_project.core.EpochTime relativeToEpoch = 3;</code>
     */
    public Builder setRelativeToEpoch(
        eu.surething_project.core.grpc.time.EpochTime.Builder builderForValue) {
      if (relativeToEpochBuilder_ == null) {
        time_ = builderForValue.build();
        onChanged();
      } else {
        relativeToEpochBuilder_.setMessage(builderForValue.build());
      }
      timeCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * time relative to epoch
     * </pre>
     *
     * <code>.eu.surething_project.core.EpochTime relativeToEpoch = 3;</code>
     */
    public Builder mergeRelativeToEpoch(eu.surething_project.core.grpc.time.EpochTime value) {
      if (relativeToEpochBuilder_ == null) {
        if (timeCase_ == 3 &&
            time_ != eu.surething_project.core.grpc.time.EpochTime.getDefaultInstance()) {
          time_ = eu.surething_project.core.grpc.time.EpochTime.newBuilder((eu.surething_project.core.grpc.time.EpochTime) time_)
              .mergeFrom(value).buildPartial();
        } else {
          time_ = value;
        }
        onChanged();
      } else {
        if (timeCase_ == 3) {
          relativeToEpochBuilder_.mergeFrom(value);
        }
        relativeToEpochBuilder_.setMessage(value);
      }
      timeCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * time relative to epoch
     * </pre>
     *
     * <code>.eu.surething_project.core.EpochTime relativeToEpoch = 3;</code>
     */
    public Builder clearRelativeToEpoch() {
      if (relativeToEpochBuilder_ == null) {
        if (timeCase_ == 3) {
          timeCase_ = 0;
          time_ = null;
          onChanged();
        }
      } else {
        if (timeCase_ == 3) {
          timeCase_ = 0;
          time_ = null;
        }
        relativeToEpochBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * time relative to epoch
     * </pre>
     *
     * <code>.eu.surething_project.core.EpochTime relativeToEpoch = 3;</code>
     */
    public eu.surething_project.core.grpc.time.EpochTime.Builder getRelativeToEpochBuilder() {
      return getRelativeToEpochFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * time relative to epoch
     * </pre>
     *
     * <code>.eu.surething_project.core.EpochTime relativeToEpoch = 3;</code>
     */
    public eu.surething_project.core.grpc.time.EpochTimeOrBuilder getRelativeToEpochOrBuilder() {
      if ((timeCase_ == 3) && (relativeToEpochBuilder_ != null)) {
        return relativeToEpochBuilder_.getMessageOrBuilder();
      } else {
        if (timeCase_ == 3) {
          return (eu.surething_project.core.grpc.time.EpochTime) time_;
        }
        return eu.surething_project.core.grpc.time.EpochTime.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * time relative to epoch
     * </pre>
     *
     * <code>.eu.surething_project.core.EpochTime relativeToEpoch = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        eu.surething_project.core.grpc.time.EpochTime, eu.surething_project.core.grpc.time.EpochTime.Builder, eu.surething_project.core.grpc.time.EpochTimeOrBuilder> 
        getRelativeToEpochFieldBuilder() {
      if (relativeToEpochBuilder_ == null) {
        if (!(timeCase_ == 3)) {
          time_ = eu.surething_project.core.grpc.time.EpochTime.getDefaultInstance();
        }
        relativeToEpochBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            eu.surething_project.core.grpc.time.EpochTime, eu.surething_project.core.grpc.time.EpochTime.Builder, eu.surething_project.core.grpc.time.EpochTimeOrBuilder>(
                (eu.surething_project.core.grpc.time.EpochTime) time_,
                getParentForChildren(),
                isClean());
        time_ = null;
      }
      timeCase_ = 3;
      onChanged();;
      return relativeToEpochBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Empty, com.google.protobuf.Empty.Builder, com.google.protobuf.EmptyOrBuilder> emptyBuilder_;
    /**
     * <pre>
     * use when we do no have time information
     * </pre>
     *
     * <code>.google.protobuf.Empty empty = 4;</code>
     */
    public boolean hasEmpty() {
      return timeCase_ == 4;
    }
    /**
     * <pre>
     * use when we do no have time information
     * </pre>
     *
     * <code>.google.protobuf.Empty empty = 4;</code>
     */
    public com.google.protobuf.Empty getEmpty() {
      if (emptyBuilder_ == null) {
        if (timeCase_ == 4) {
          return (com.google.protobuf.Empty) time_;
        }
        return com.google.protobuf.Empty.getDefaultInstance();
      } else {
        if (timeCase_ == 4) {
          return emptyBuilder_.getMessage();
        }
        return com.google.protobuf.Empty.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * use when we do no have time information
     * </pre>
     *
     * <code>.google.protobuf.Empty empty = 4;</code>
     */
    public Builder setEmpty(com.google.protobuf.Empty value) {
      if (emptyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        time_ = value;
        onChanged();
      } else {
        emptyBuilder_.setMessage(value);
      }
      timeCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * use when we do no have time information
     * </pre>
     *
     * <code>.google.protobuf.Empty empty = 4;</code>
     */
    public Builder setEmpty(
        com.google.protobuf.Empty.Builder builderForValue) {
      if (emptyBuilder_ == null) {
        time_ = builderForValue.build();
        onChanged();
      } else {
        emptyBuilder_.setMessage(builderForValue.build());
      }
      timeCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * use when we do no have time information
     * </pre>
     *
     * <code>.google.protobuf.Empty empty = 4;</code>
     */
    public Builder mergeEmpty(com.google.protobuf.Empty value) {
      if (emptyBuilder_ == null) {
        if (timeCase_ == 4 &&
            time_ != com.google.protobuf.Empty.getDefaultInstance()) {
          time_ = com.google.protobuf.Empty.newBuilder((com.google.protobuf.Empty) time_)
              .mergeFrom(value).buildPartial();
        } else {
          time_ = value;
        }
        onChanged();
      } else {
        if (timeCase_ == 4) {
          emptyBuilder_.mergeFrom(value);
        }
        emptyBuilder_.setMessage(value);
      }
      timeCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * use when we do no have time information
     * </pre>
     *
     * <code>.google.protobuf.Empty empty = 4;</code>
     */
    public Builder clearEmpty() {
      if (emptyBuilder_ == null) {
        if (timeCase_ == 4) {
          timeCase_ = 0;
          time_ = null;
          onChanged();
        }
      } else {
        if (timeCase_ == 4) {
          timeCase_ = 0;
          time_ = null;
        }
        emptyBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * use when we do no have time information
     * </pre>
     *
     * <code>.google.protobuf.Empty empty = 4;</code>
     */
    public com.google.protobuf.Empty.Builder getEmptyBuilder() {
      return getEmptyFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * use when we do no have time information
     * </pre>
     *
     * <code>.google.protobuf.Empty empty = 4;</code>
     */
    public com.google.protobuf.EmptyOrBuilder getEmptyOrBuilder() {
      if ((timeCase_ == 4) && (emptyBuilder_ != null)) {
        return emptyBuilder_.getMessageOrBuilder();
      } else {
        if (timeCase_ == 4) {
          return (com.google.protobuf.Empty) time_;
        }
        return com.google.protobuf.Empty.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * use when we do no have time information
     * </pre>
     *
     * <code>.google.protobuf.Empty empty = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Empty, com.google.protobuf.Empty.Builder, com.google.protobuf.EmptyOrBuilder> 
        getEmptyFieldBuilder() {
      if (emptyBuilder_ == null) {
        if (!(timeCase_ == 4)) {
          time_ = com.google.protobuf.Empty.getDefaultInstance();
        }
        emptyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Empty, com.google.protobuf.Empty.Builder, com.google.protobuf.EmptyOrBuilder>(
                (com.google.protobuf.Empty) time_,
                getParentForChildren(),
                isClean());
        time_ = null;
      }
      timeCase_ = 4;
      onChanged();;
      return emptyBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:eu.surething_project.core.Time)
  }

  // @@protoc_insertion_point(class_scope:eu.surething_project.core.Time)
  private static final eu.surething_project.core.grpc.time.Time DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new eu.surething_project.core.grpc.time.Time();
  }

  public static eu.surething_project.core.grpc.time.Time getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Time>
      PARSER = new com.google.protobuf.AbstractParser<Time>() {
    @java.lang.Override
    public Time parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Time(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Time> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Time> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public eu.surething_project.core.grpc.time.Time getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

