// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loc_cert.proto

package eu.surething_project.core.grpc;

public interface LocationCertificateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eu.surething_project.core.LocationCertificate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.eu.surething_project.core.LocationVerification verification = 1;</code>
   */
  boolean hasVerification();
  /**
   * <code>.eu.surething_project.core.LocationVerification verification = 1;</code>
   */
  eu.surething_project.core.grpc.LocationVerification getVerification();
  /**
   * <code>.eu.surething_project.core.LocationVerification verification = 1;</code>
   */
  eu.surething_project.core.grpc.LocationVerificationOrBuilder getVerificationOrBuilder();

  /**
   * <code>.eu.surething_project.core.Signature verifierSignature = 2;</code>
   */
  boolean hasVerifierSignature();
  /**
   * <code>.eu.surething_project.core.Signature verifierSignature = 2;</code>
   */
  eu.surething_project.core.grpc.Signature getVerifierSignature();
  /**
   * <code>.eu.surething_project.core.Signature verifierSignature = 2;</code>
   */
  eu.surething_project.core.grpc.SignatureOrBuilder getVerifierSignatureOrBuilder();
}
