// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wi_fi.proto

package eu.surething_project.core.grpc;

public interface WiFiNetworksEvidenceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eu.surething_project.core.WiFiNetworksEvidence)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * unique id
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <pre>
   * unique id
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * detected APs
   * </pre>
   *
   * <code>repeated .eu.surething_project.core.WiFiNetworksEvidence.AP aps = 2;</code>
   */
  java.util.List<eu.surething_project.core.grpc.WiFiNetworksEvidence.AP> 
      getApsList();
  /**
   * <pre>
   * detected APs
   * </pre>
   *
   * <code>repeated .eu.surething_project.core.WiFiNetworksEvidence.AP aps = 2;</code>
   */
  eu.surething_project.core.grpc.WiFiNetworksEvidence.AP getAps(int index);
  /**
   * <pre>
   * detected APs
   * </pre>
   *
   * <code>repeated .eu.surething_project.core.WiFiNetworksEvidence.AP aps = 2;</code>
   */
  int getApsCount();
  /**
   * <pre>
   * detected APs
   * </pre>
   *
   * <code>repeated .eu.surething_project.core.WiFiNetworksEvidence.AP aps = 2;</code>
   */
  java.util.List<? extends eu.surething_project.core.grpc.WiFiNetworksEvidence.APOrBuilder> 
      getApsOrBuilderList();
  /**
   * <pre>
   * detected APs
   * </pre>
   *
   * <code>repeated .eu.surething_project.core.WiFiNetworksEvidence.AP aps = 2;</code>
   */
  eu.surething_project.core.grpc.WiFiNetworksEvidence.APOrBuilder getApsOrBuilder(
      int index);
}
