// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loc_claim.proto

package eu.surething_project.core.grpc;

public final class LocClaimProto {
  private LocClaimProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_surething_project_core_LocationClaim_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eu_surething_project_core_LocationClaim_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_surething_project_core_SignedLocationClaim_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eu_surething_project_core_SignedLocationClaim_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017loc_claim.proto\022\031eu.surething_project." +
      "core\032\031google/protobuf/any.proto\032\016loc_tim" +
      "e.proto\032\017signature.proto\"\326\001\n\rLocationCla" +
      "im\022\017\n\007claimId\030\001 \001(\t\022\020\n\010proverId\030\002 \001(\t\0225\n" +
      "\010location\030\003 \001(\0132#.eu.surething_project.c" +
      "ore.Location\022-\n\004time\030\004 \001(\0132\037.eu.surethin" +
      "g_project.core.Time\022\024\n\014evidenceType\030\005 \001(" +
      "\t\022&\n\010evidence\030\006 \001(\0132\024.google.protobuf.An" +
      "y\"\215\001\n\023SignedLocationClaim\0227\n\005claim\030\001 \001(\013" +
      "2(.eu.surething_project.core.LocationCla" +
      "im\022=\n\017proverSignature\030\002 \001(\0132$.eu.surethi" +
      "ng_project.core.SignatureB1\n\036eu.surethin" +
      "g_project.core.grpcB\rLocClaimProtoP\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          eu.surething_project.core.grpc.LocTimeProto.getDescriptor(),
          eu.surething_project.core.grpc.SignatureProto.getDescriptor(),
        }, assigner);
    internal_static_eu_surething_project_core_LocationClaim_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_eu_surething_project_core_LocationClaim_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eu_surething_project_core_LocationClaim_descriptor,
        new java.lang.String[] { "ClaimId", "ProverId", "Location", "Time", "EvidenceType", "Evidence", });
    internal_static_eu_surething_project_core_SignedLocationClaim_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_eu_surething_project_core_SignedLocationClaim_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eu_surething_project_core_SignedLocationClaim_descriptor,
        new java.lang.String[] { "Claim", "ProverSignature", });
    com.google.protobuf.AnyProto.getDescriptor();
    eu.surething_project.core.grpc.LocTimeProto.getDescriptor();
    eu.surething_project.core.grpc.SignatureProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
