// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wi_fi.proto

package eu.surething_project.core.grpc;

/**
 * <pre>
 * Wi-Fi networks evidence 
 * </pre>
 *
 * Protobuf type {@code eu.surething_project.core.WiFiNetworksEvidence}
 */
public  final class WiFiNetworksEvidence extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:eu.surething_project.core.WiFiNetworksEvidence)
    WiFiNetworksEvidenceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WiFiNetworksEvidence.newBuilder() to construct.
  private WiFiNetworksEvidence(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WiFiNetworksEvidence() {
    id_ = "";
    aps_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WiFiNetworksEvidence(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              aps_ = new java.util.ArrayList<eu.surething_project.core.grpc.WiFiNetworksEvidence.AP>();
              mutable_bitField0_ |= 0x00000002;
            }
            aps_.add(
                input.readMessage(eu.surething_project.core.grpc.WiFiNetworksEvidence.AP.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        aps_ = java.util.Collections.unmodifiableList(aps_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return eu.surething_project.core.grpc.WiFiProto.internal_static_eu_surething_project_core_WiFiNetworksEvidence_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return eu.surething_project.core.grpc.WiFiProto.internal_static_eu_surething_project_core_WiFiNetworksEvidence_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            eu.surething_project.core.grpc.WiFiNetworksEvidence.class, eu.surething_project.core.grpc.WiFiNetworksEvidence.Builder.class);
  }

  public interface APOrBuilder extends
      // @@protoc_insertion_point(interface_extends:eu.surething_project.core.WiFiNetworksEvidence.AP)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * AP identifier
     * </pre>
     *
     * <code>string ssid = 1;</code>
     */
    java.lang.String getSsid();
    /**
     * <pre>
     * AP identifier
     * </pre>
     *
     * <code>string ssid = 1;</code>
     */
    com.google.protobuf.ByteString
        getSsidBytes();

    /**
     * <pre>
     * measured RSSI 
     * </pre>
     *
     * <code>string rssi = 2;</code>
     */
    java.lang.String getRssi();
    /**
     * <pre>
     * measured RSSI 
     * </pre>
     *
     * <code>string rssi = 2;</code>
     */
    com.google.protobuf.ByteString
        getRssiBytes();
  }
  /**
   * <pre>
   * Access point (AP) definition
   * </pre>
   *
   * Protobuf type {@code eu.surething_project.core.WiFiNetworksEvidence.AP}
   */
  public  static final class AP extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:eu.surething_project.core.WiFiNetworksEvidence.AP)
      APOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AP.newBuilder() to construct.
    private AP(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AP() {
      ssid_ = "";
      rssi_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AP(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              ssid_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              rssi_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.surething_project.core.grpc.WiFiProto.internal_static_eu_surething_project_core_WiFiNetworksEvidence_AP_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.surething_project.core.grpc.WiFiProto.internal_static_eu_surething_project_core_WiFiNetworksEvidence_AP_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.surething_project.core.grpc.WiFiNetworksEvidence.AP.class, eu.surething_project.core.grpc.WiFiNetworksEvidence.AP.Builder.class);
    }

    public static final int SSID_FIELD_NUMBER = 1;
    private volatile java.lang.Object ssid_;
    /**
     * <pre>
     * AP identifier
     * </pre>
     *
     * <code>string ssid = 1;</code>
     */
    public java.lang.String getSsid() {
      java.lang.Object ref = ssid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ssid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * AP identifier
     * </pre>
     *
     * <code>string ssid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSsidBytes() {
      java.lang.Object ref = ssid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ssid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RSSI_FIELD_NUMBER = 2;
    private volatile java.lang.Object rssi_;
    /**
     * <pre>
     * measured RSSI 
     * </pre>
     *
     * <code>string rssi = 2;</code>
     */
    public java.lang.String getRssi() {
      java.lang.Object ref = rssi_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rssi_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * measured RSSI 
     * </pre>
     *
     * <code>string rssi = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRssiBytes() {
      java.lang.Object ref = rssi_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rssi_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSsidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ssid_);
      }
      if (!getRssiBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, rssi_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSsidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ssid_);
      }
      if (!getRssiBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, rssi_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof eu.surething_project.core.grpc.WiFiNetworksEvidence.AP)) {
        return super.equals(obj);
      }
      eu.surething_project.core.grpc.WiFiNetworksEvidence.AP other = (eu.surething_project.core.grpc.WiFiNetworksEvidence.AP) obj;

      boolean result = true;
      result = result && getSsid()
          .equals(other.getSsid());
      result = result && getRssi()
          .equals(other.getRssi());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SSID_FIELD_NUMBER;
      hash = (53 * hash) + getSsid().hashCode();
      hash = (37 * hash) + RSSI_FIELD_NUMBER;
      hash = (53 * hash) + getRssi().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static eu.surething_project.core.grpc.WiFiNetworksEvidence.AP parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.surething_project.core.grpc.WiFiNetworksEvidence.AP parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.surething_project.core.grpc.WiFiNetworksEvidence.AP parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.surething_project.core.grpc.WiFiNetworksEvidence.AP parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.surething_project.core.grpc.WiFiNetworksEvidence.AP parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.surething_project.core.grpc.WiFiNetworksEvidence.AP parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.surething_project.core.grpc.WiFiNetworksEvidence.AP parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static eu.surething_project.core.grpc.WiFiNetworksEvidence.AP parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static eu.surething_project.core.grpc.WiFiNetworksEvidence.AP parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static eu.surething_project.core.grpc.WiFiNetworksEvidence.AP parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static eu.surething_project.core.grpc.WiFiNetworksEvidence.AP parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static eu.surething_project.core.grpc.WiFiNetworksEvidence.AP parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(eu.surething_project.core.grpc.WiFiNetworksEvidence.AP prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Access point (AP) definition
     * </pre>
     *
     * Protobuf type {@code eu.surething_project.core.WiFiNetworksEvidence.AP}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:eu.surething_project.core.WiFiNetworksEvidence.AP)
        eu.surething_project.core.grpc.WiFiNetworksEvidence.APOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.surething_project.core.grpc.WiFiProto.internal_static_eu_surething_project_core_WiFiNetworksEvidence_AP_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.surething_project.core.grpc.WiFiProto.internal_static_eu_surething_project_core_WiFiNetworksEvidence_AP_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                eu.surething_project.core.grpc.WiFiNetworksEvidence.AP.class, eu.surething_project.core.grpc.WiFiNetworksEvidence.AP.Builder.class);
      }

      // Construct using eu.surething_project.core.grpc.WiFiNetworksEvidence.AP.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ssid_ = "";

        rssi_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.surething_project.core.grpc.WiFiProto.internal_static_eu_surething_project_core_WiFiNetworksEvidence_AP_descriptor;
      }

      @java.lang.Override
      public eu.surething_project.core.grpc.WiFiNetworksEvidence.AP getDefaultInstanceForType() {
        return eu.surething_project.core.grpc.WiFiNetworksEvidence.AP.getDefaultInstance();
      }

      @java.lang.Override
      public eu.surething_project.core.grpc.WiFiNetworksEvidence.AP build() {
        eu.surething_project.core.grpc.WiFiNetworksEvidence.AP result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public eu.surething_project.core.grpc.WiFiNetworksEvidence.AP buildPartial() {
        eu.surething_project.core.grpc.WiFiNetworksEvidence.AP result = new eu.surething_project.core.grpc.WiFiNetworksEvidence.AP(this);
        result.ssid_ = ssid_;
        result.rssi_ = rssi_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.surething_project.core.grpc.WiFiNetworksEvidence.AP) {
          return mergeFrom((eu.surething_project.core.grpc.WiFiNetworksEvidence.AP)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(eu.surething_project.core.grpc.WiFiNetworksEvidence.AP other) {
        if (other == eu.surething_project.core.grpc.WiFiNetworksEvidence.AP.getDefaultInstance()) return this;
        if (!other.getSsid().isEmpty()) {
          ssid_ = other.ssid_;
          onChanged();
        }
        if (!other.getRssi().isEmpty()) {
          rssi_ = other.rssi_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        eu.surething_project.core.grpc.WiFiNetworksEvidence.AP parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (eu.surething_project.core.grpc.WiFiNetworksEvidence.AP) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object ssid_ = "";
      /**
       * <pre>
       * AP identifier
       * </pre>
       *
       * <code>string ssid = 1;</code>
       */
      public java.lang.String getSsid() {
        java.lang.Object ref = ssid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ssid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * AP identifier
       * </pre>
       *
       * <code>string ssid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSsidBytes() {
        java.lang.Object ref = ssid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ssid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * AP identifier
       * </pre>
       *
       * <code>string ssid = 1;</code>
       */
      public Builder setSsid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ssid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * AP identifier
       * </pre>
       *
       * <code>string ssid = 1;</code>
       */
      public Builder clearSsid() {
        
        ssid_ = getDefaultInstance().getSsid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * AP identifier
       * </pre>
       *
       * <code>string ssid = 1;</code>
       */
      public Builder setSsidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ssid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object rssi_ = "";
      /**
       * <pre>
       * measured RSSI 
       * </pre>
       *
       * <code>string rssi = 2;</code>
       */
      public java.lang.String getRssi() {
        java.lang.Object ref = rssi_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rssi_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * measured RSSI 
       * </pre>
       *
       * <code>string rssi = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRssiBytes() {
        java.lang.Object ref = rssi_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rssi_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * measured RSSI 
       * </pre>
       *
       * <code>string rssi = 2;</code>
       */
      public Builder setRssi(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rssi_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * measured RSSI 
       * </pre>
       *
       * <code>string rssi = 2;</code>
       */
      public Builder clearRssi() {
        
        rssi_ = getDefaultInstance().getRssi();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * measured RSSI 
       * </pre>
       *
       * <code>string rssi = 2;</code>
       */
      public Builder setRssiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rssi_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:eu.surething_project.core.WiFiNetworksEvidence.AP)
    }

    // @@protoc_insertion_point(class_scope:eu.surething_project.core.WiFiNetworksEvidence.AP)
    private static final eu.surething_project.core.grpc.WiFiNetworksEvidence.AP DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new eu.surething_project.core.grpc.WiFiNetworksEvidence.AP();
    }

    public static eu.surething_project.core.grpc.WiFiNetworksEvidence.AP getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AP>
        PARSER = new com.google.protobuf.AbstractParser<AP>() {
      @java.lang.Override
      public AP parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AP(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AP> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AP> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public eu.surething_project.core.grpc.WiFiNetworksEvidence.AP getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <pre>
   * unique id
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * unique id
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APS_FIELD_NUMBER = 2;
  private java.util.List<eu.surething_project.core.grpc.WiFiNetworksEvidence.AP> aps_;
  /**
   * <pre>
   * detected APs
   * </pre>
   *
   * <code>repeated .eu.surething_project.core.WiFiNetworksEvidence.AP aps = 2;</code>
   */
  public java.util.List<eu.surething_project.core.grpc.WiFiNetworksEvidence.AP> getApsList() {
    return aps_;
  }
  /**
   * <pre>
   * detected APs
   * </pre>
   *
   * <code>repeated .eu.surething_project.core.WiFiNetworksEvidence.AP aps = 2;</code>
   */
  public java.util.List<? extends eu.surething_project.core.grpc.WiFiNetworksEvidence.APOrBuilder> 
      getApsOrBuilderList() {
    return aps_;
  }
  /**
   * <pre>
   * detected APs
   * </pre>
   *
   * <code>repeated .eu.surething_project.core.WiFiNetworksEvidence.AP aps = 2;</code>
   */
  public int getApsCount() {
    return aps_.size();
  }
  /**
   * <pre>
   * detected APs
   * </pre>
   *
   * <code>repeated .eu.surething_project.core.WiFiNetworksEvidence.AP aps = 2;</code>
   */
  public eu.surething_project.core.grpc.WiFiNetworksEvidence.AP getAps(int index) {
    return aps_.get(index);
  }
  /**
   * <pre>
   * detected APs
   * </pre>
   *
   * <code>repeated .eu.surething_project.core.WiFiNetworksEvidence.AP aps = 2;</code>
   */
  public eu.surething_project.core.grpc.WiFiNetworksEvidence.APOrBuilder getApsOrBuilder(
      int index) {
    return aps_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    for (int i = 0; i < aps_.size(); i++) {
      output.writeMessage(2, aps_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    for (int i = 0; i < aps_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, aps_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof eu.surething_project.core.grpc.WiFiNetworksEvidence)) {
      return super.equals(obj);
    }
    eu.surething_project.core.grpc.WiFiNetworksEvidence other = (eu.surething_project.core.grpc.WiFiNetworksEvidence) obj;

    boolean result = true;
    result = result && getId()
        .equals(other.getId());
    result = result && getApsList()
        .equals(other.getApsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (getApsCount() > 0) {
      hash = (37 * hash) + APS_FIELD_NUMBER;
      hash = (53 * hash) + getApsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static eu.surething_project.core.grpc.WiFiNetworksEvidence parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.surething_project.core.grpc.WiFiNetworksEvidence parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.WiFiNetworksEvidence parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.surething_project.core.grpc.WiFiNetworksEvidence parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.WiFiNetworksEvidence parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.surething_project.core.grpc.WiFiNetworksEvidence parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.WiFiNetworksEvidence parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.surething_project.core.grpc.WiFiNetworksEvidence parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.WiFiNetworksEvidence parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static eu.surething_project.core.grpc.WiFiNetworksEvidence parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.WiFiNetworksEvidence parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.surething_project.core.grpc.WiFiNetworksEvidence parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(eu.surething_project.core.grpc.WiFiNetworksEvidence prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Wi-Fi networks evidence 
   * </pre>
   *
   * Protobuf type {@code eu.surething_project.core.WiFiNetworksEvidence}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:eu.surething_project.core.WiFiNetworksEvidence)
      eu.surething_project.core.grpc.WiFiNetworksEvidenceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.surething_project.core.grpc.WiFiProto.internal_static_eu_surething_project_core_WiFiNetworksEvidence_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.surething_project.core.grpc.WiFiProto.internal_static_eu_surething_project_core_WiFiNetworksEvidence_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.surething_project.core.grpc.WiFiNetworksEvidence.class, eu.surething_project.core.grpc.WiFiNetworksEvidence.Builder.class);
    }

    // Construct using eu.surething_project.core.grpc.WiFiNetworksEvidence.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getApsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      if (apsBuilder_ == null) {
        aps_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        apsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return eu.surething_project.core.grpc.WiFiProto.internal_static_eu_surething_project_core_WiFiNetworksEvidence_descriptor;
    }

    @java.lang.Override
    public eu.surething_project.core.grpc.WiFiNetworksEvidence getDefaultInstanceForType() {
      return eu.surething_project.core.grpc.WiFiNetworksEvidence.getDefaultInstance();
    }

    @java.lang.Override
    public eu.surething_project.core.grpc.WiFiNetworksEvidence build() {
      eu.surething_project.core.grpc.WiFiNetworksEvidence result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public eu.surething_project.core.grpc.WiFiNetworksEvidence buildPartial() {
      eu.surething_project.core.grpc.WiFiNetworksEvidence result = new eu.surething_project.core.grpc.WiFiNetworksEvidence(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      if (apsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          aps_ = java.util.Collections.unmodifiableList(aps_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.aps_ = aps_;
      } else {
        result.aps_ = apsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof eu.surething_project.core.grpc.WiFiNetworksEvidence) {
        return mergeFrom((eu.surething_project.core.grpc.WiFiNetworksEvidence)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(eu.surething_project.core.grpc.WiFiNetworksEvidence other) {
      if (other == eu.surething_project.core.grpc.WiFiNetworksEvidence.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (apsBuilder_ == null) {
        if (!other.aps_.isEmpty()) {
          if (aps_.isEmpty()) {
            aps_ = other.aps_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureApsIsMutable();
            aps_.addAll(other.aps_);
          }
          onChanged();
        }
      } else {
        if (!other.aps_.isEmpty()) {
          if (apsBuilder_.isEmpty()) {
            apsBuilder_.dispose();
            apsBuilder_ = null;
            aps_ = other.aps_;
            bitField0_ = (bitField0_ & ~0x00000002);
            apsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getApsFieldBuilder() : null;
          } else {
            apsBuilder_.addAllMessages(other.aps_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      eu.surething_project.core.grpc.WiFiNetworksEvidence parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (eu.surething_project.core.grpc.WiFiNetworksEvidence) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <pre>
     * unique id
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * unique id
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * unique id
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unique id
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unique id
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.util.List<eu.surething_project.core.grpc.WiFiNetworksEvidence.AP> aps_ =
      java.util.Collections.emptyList();
    private void ensureApsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        aps_ = new java.util.ArrayList<eu.surething_project.core.grpc.WiFiNetworksEvidence.AP>(aps_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        eu.surething_project.core.grpc.WiFiNetworksEvidence.AP, eu.surething_project.core.grpc.WiFiNetworksEvidence.AP.Builder, eu.surething_project.core.grpc.WiFiNetworksEvidence.APOrBuilder> apsBuilder_;

    /**
     * <pre>
     * detected APs
     * </pre>
     *
     * <code>repeated .eu.surething_project.core.WiFiNetworksEvidence.AP aps = 2;</code>
     */
    public java.util.List<eu.surething_project.core.grpc.WiFiNetworksEvidence.AP> getApsList() {
      if (apsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(aps_);
      } else {
        return apsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * detected APs
     * </pre>
     *
     * <code>repeated .eu.surething_project.core.WiFiNetworksEvidence.AP aps = 2;</code>
     */
    public int getApsCount() {
      if (apsBuilder_ == null) {
        return aps_.size();
      } else {
        return apsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * detected APs
     * </pre>
     *
     * <code>repeated .eu.surething_project.core.WiFiNetworksEvidence.AP aps = 2;</code>
     */
    public eu.surething_project.core.grpc.WiFiNetworksEvidence.AP getAps(int index) {
      if (apsBuilder_ == null) {
        return aps_.get(index);
      } else {
        return apsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * detected APs
     * </pre>
     *
     * <code>repeated .eu.surething_project.core.WiFiNetworksEvidence.AP aps = 2;</code>
     */
    public Builder setAps(
        int index, eu.surething_project.core.grpc.WiFiNetworksEvidence.AP value) {
      if (apsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureApsIsMutable();
        aps_.set(index, value);
        onChanged();
      } else {
        apsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * detected APs
     * </pre>
     *
     * <code>repeated .eu.surething_project.core.WiFiNetworksEvidence.AP aps = 2;</code>
     */
    public Builder setAps(
        int index, eu.surething_project.core.grpc.WiFiNetworksEvidence.AP.Builder builderForValue) {
      if (apsBuilder_ == null) {
        ensureApsIsMutable();
        aps_.set(index, builderForValue.build());
        onChanged();
      } else {
        apsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * detected APs
     * </pre>
     *
     * <code>repeated .eu.surething_project.core.WiFiNetworksEvidence.AP aps = 2;</code>
     */
    public Builder addAps(eu.surething_project.core.grpc.WiFiNetworksEvidence.AP value) {
      if (apsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureApsIsMutable();
        aps_.add(value);
        onChanged();
      } else {
        apsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * detected APs
     * </pre>
     *
     * <code>repeated .eu.surething_project.core.WiFiNetworksEvidence.AP aps = 2;</code>
     */
    public Builder addAps(
        int index, eu.surething_project.core.grpc.WiFiNetworksEvidence.AP value) {
      if (apsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureApsIsMutable();
        aps_.add(index, value);
        onChanged();
      } else {
        apsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * detected APs
     * </pre>
     *
     * <code>repeated .eu.surething_project.core.WiFiNetworksEvidence.AP aps = 2;</code>
     */
    public Builder addAps(
        eu.surething_project.core.grpc.WiFiNetworksEvidence.AP.Builder builderForValue) {
      if (apsBuilder_ == null) {
        ensureApsIsMutable();
        aps_.add(builderForValue.build());
        onChanged();
      } else {
        apsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * detected APs
     * </pre>
     *
     * <code>repeated .eu.surething_project.core.WiFiNetworksEvidence.AP aps = 2;</code>
     */
    public Builder addAps(
        int index, eu.surething_project.core.grpc.WiFiNetworksEvidence.AP.Builder builderForValue) {
      if (apsBuilder_ == null) {
        ensureApsIsMutable();
        aps_.add(index, builderForValue.build());
        onChanged();
      } else {
        apsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * detected APs
     * </pre>
     *
     * <code>repeated .eu.surething_project.core.WiFiNetworksEvidence.AP aps = 2;</code>
     */
    public Builder addAllAps(
        java.lang.Iterable<? extends eu.surething_project.core.grpc.WiFiNetworksEvidence.AP> values) {
      if (apsBuilder_ == null) {
        ensureApsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, aps_);
        onChanged();
      } else {
        apsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * detected APs
     * </pre>
     *
     * <code>repeated .eu.surething_project.core.WiFiNetworksEvidence.AP aps = 2;</code>
     */
    public Builder clearAps() {
      if (apsBuilder_ == null) {
        aps_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        apsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * detected APs
     * </pre>
     *
     * <code>repeated .eu.surething_project.core.WiFiNetworksEvidence.AP aps = 2;</code>
     */
    public Builder removeAps(int index) {
      if (apsBuilder_ == null) {
        ensureApsIsMutable();
        aps_.remove(index);
        onChanged();
      } else {
        apsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * detected APs
     * </pre>
     *
     * <code>repeated .eu.surething_project.core.WiFiNetworksEvidence.AP aps = 2;</code>
     */
    public eu.surething_project.core.grpc.WiFiNetworksEvidence.AP.Builder getApsBuilder(
        int index) {
      return getApsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * detected APs
     * </pre>
     *
     * <code>repeated .eu.surething_project.core.WiFiNetworksEvidence.AP aps = 2;</code>
     */
    public eu.surething_project.core.grpc.WiFiNetworksEvidence.APOrBuilder getApsOrBuilder(
        int index) {
      if (apsBuilder_ == null) {
        return aps_.get(index);  } else {
        return apsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * detected APs
     * </pre>
     *
     * <code>repeated .eu.surething_project.core.WiFiNetworksEvidence.AP aps = 2;</code>
     */
    public java.util.List<? extends eu.surething_project.core.grpc.WiFiNetworksEvidence.APOrBuilder> 
         getApsOrBuilderList() {
      if (apsBuilder_ != null) {
        return apsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(aps_);
      }
    }
    /**
     * <pre>
     * detected APs
     * </pre>
     *
     * <code>repeated .eu.surething_project.core.WiFiNetworksEvidence.AP aps = 2;</code>
     */
    public eu.surething_project.core.grpc.WiFiNetworksEvidence.AP.Builder addApsBuilder() {
      return getApsFieldBuilder().addBuilder(
          eu.surething_project.core.grpc.WiFiNetworksEvidence.AP.getDefaultInstance());
    }
    /**
     * <pre>
     * detected APs
     * </pre>
     *
     * <code>repeated .eu.surething_project.core.WiFiNetworksEvidence.AP aps = 2;</code>
     */
    public eu.surething_project.core.grpc.WiFiNetworksEvidence.AP.Builder addApsBuilder(
        int index) {
      return getApsFieldBuilder().addBuilder(
          index, eu.surething_project.core.grpc.WiFiNetworksEvidence.AP.getDefaultInstance());
    }
    /**
     * <pre>
     * detected APs
     * </pre>
     *
     * <code>repeated .eu.surething_project.core.WiFiNetworksEvidence.AP aps = 2;</code>
     */
    public java.util.List<eu.surething_project.core.grpc.WiFiNetworksEvidence.AP.Builder> 
         getApsBuilderList() {
      return getApsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        eu.surething_project.core.grpc.WiFiNetworksEvidence.AP, eu.surething_project.core.grpc.WiFiNetworksEvidence.AP.Builder, eu.surething_project.core.grpc.WiFiNetworksEvidence.APOrBuilder> 
        getApsFieldBuilder() {
      if (apsBuilder_ == null) {
        apsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            eu.surething_project.core.grpc.WiFiNetworksEvidence.AP, eu.surething_project.core.grpc.WiFiNetworksEvidence.AP.Builder, eu.surething_project.core.grpc.WiFiNetworksEvidence.APOrBuilder>(
                aps_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        aps_ = null;
      }
      return apsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:eu.surething_project.core.WiFiNetworksEvidence)
  }

  // @@protoc_insertion_point(class_scope:eu.surething_project.core.WiFiNetworksEvidence)
  private static final eu.surething_project.core.grpc.WiFiNetworksEvidence DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new eu.surething_project.core.grpc.WiFiNetworksEvidence();
  }

  public static eu.surething_project.core.grpc.WiFiNetworksEvidence getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WiFiNetworksEvidence>
      PARSER = new com.google.protobuf.AbstractParser<WiFiNetworksEvidence>() {
    @java.lang.Override
    public WiFiNetworksEvidence parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WiFiNetworksEvidence(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WiFiNetworksEvidence> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WiFiNetworksEvidence> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public eu.surething_project.core.grpc.WiFiNetworksEvidence getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

