# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: loc_cert.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from . import loc_time_pb2 as loc__time__pb2
from . import signature_pb2 as signature__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='loc_cert.proto',
  package='eu.surething_project.core',
  syntax='proto3',
  serialized_options=b'\n\031eu.surething_project.coreB\014LocCertProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eloc_cert.proto\x12\x19\x65u.surething_project.core\x1a\x19google/protobuf/any.proto\x1a\x0eloc_time.proto\x1a\x0fsignature.proto\"\xc0\x01\n\x14LocationVerification\x12\x12\n\nverifierId\x18\x01 \x01(\t\x12\x0f\n\x07\x63laimId\x18\x02 \x01(\t\x12\x16\n\x0e\x65ndorsementIds\x18\x03 \x03(\t\x12-\n\x04time\x18\x04 \x01(\x0b\x32\x1f.eu.surething_project.core.Time\x12\x14\n\x0c\x65videnceType\x18\x05 \x01(\t\x12&\n\x08\x65vidence\x18\x06 \x01(\x0b\x32\x14.google.protobuf.Any\"\x95\x01\n\x13LocationCertificate\x12\x45\n\x0cverification\x18\x01 \x01(\x0b\x32/.eu.surething_project.core.LocationVerification\x12\x37\n\tsignature\x18\x02 \x01(\x0b\x32$.eu.surething_project.core.SignatureB+\n\x19\x65u.surething_project.coreB\x0cLocCertProtoP\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,loc__time__pb2.DESCRIPTOR,signature__pb2.DESCRIPTOR,])




_LOCATIONVERIFICATION = _descriptor.Descriptor(
  name='LocationVerification',
  full_name='eu.surething_project.core.LocationVerification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='verifierId', full_name='eu.surething_project.core.LocationVerification.verifierId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='claimId', full_name='eu.surething_project.core.LocationVerification.claimId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='endorsementIds', full_name='eu.surething_project.core.LocationVerification.endorsementIds', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='eu.surething_project.core.LocationVerification.time', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='evidenceType', full_name='eu.surething_project.core.LocationVerification.evidenceType', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='evidence', full_name='eu.surething_project.core.LocationVerification.evidence', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=298,
)


_LOCATIONCERTIFICATE = _descriptor.Descriptor(
  name='LocationCertificate',
  full_name='eu.surething_project.core.LocationCertificate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='verification', full_name='eu.surething_project.core.LocationCertificate.verification', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signature', full_name='eu.surething_project.core.LocationCertificate.signature', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=450,
)

_LOCATIONVERIFICATION.fields_by_name['time'].message_type = loc__time__pb2._TIME
_LOCATIONVERIFICATION.fields_by_name['evidence'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_LOCATIONCERTIFICATE.fields_by_name['verification'].message_type = _LOCATIONVERIFICATION
_LOCATIONCERTIFICATE.fields_by_name['signature'].message_type = signature__pb2._SIGNATURE
DESCRIPTOR.message_types_by_name['LocationVerification'] = _LOCATIONVERIFICATION
DESCRIPTOR.message_types_by_name['LocationCertificate'] = _LOCATIONCERTIFICATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LocationVerification = _reflection.GeneratedProtocolMessageType('LocationVerification', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONVERIFICATION,
  '__module__' : 'loc_cert_pb2'
  # @@protoc_insertion_point(class_scope:eu.surething_project.core.LocationVerification)
  })
_sym_db.RegisterMessage(LocationVerification)

LocationCertificate = _reflection.GeneratedProtocolMessageType('LocationCertificate', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONCERTIFICATE,
  '__module__' : 'loc_cert_pb2'
  # @@protoc_insertion_point(class_scope:eu.surething_project.core.LocationCertificate)
  })
_sym_db.RegisterMessage(LocationCertificate)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
