# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: loc_claim.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from . import loc_time_pb2 as loc__time__pb2
from . import signature_pb2 as signature__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='loc_claim.proto',
  package='eu.surething_project.core',
  syntax='proto3',
  serialized_options=b'\n\031eu.surething_project.coreB\rLocClaimProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0floc_claim.proto\x12\x19\x65u.surething_project.core\x1a\x19google/protobuf/any.proto\x1a\x0eloc_time.proto\x1a\x0fsignature.proto\"\xd6\x01\n\rLocationClaim\x12\x0f\n\x07\x63laimId\x18\x01 \x01(\t\x12\x10\n\x08proverId\x18\x02 \x01(\t\x12\x35\n\x08location\x18\x03 \x01(\x0b\x32#.eu.surething_project.core.Location\x12-\n\x04time\x18\x04 \x01(\x0b\x32\x1f.eu.surething_project.core.Time\x12\x14\n\x0c\x65videnceType\x18\x05 \x01(\t\x12&\n\x08\x65vidence\x18\x06 \x01(\x0b\x32\x14.google.protobuf.Any\"\x8d\x01\n\x13SignedLocationClaim\x12\x37\n\x05\x63laim\x18\x01 \x01(\x0b\x32(.eu.surething_project.core.LocationClaim\x12=\n\x0fproverSignature\x18\x02 \x01(\x0b\x32$.eu.surething_project.core.SignatureB,\n\x19\x65u.surething_project.coreB\rLocClaimProtoP\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,loc__time__pb2.DESCRIPTOR,signature__pb2.DESCRIPTOR,])




_LOCATIONCLAIM = _descriptor.Descriptor(
  name='LocationClaim',
  full_name='eu.surething_project.core.LocationClaim',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='claimId', full_name='eu.surething_project.core.LocationClaim.claimId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='proverId', full_name='eu.surething_project.core.LocationClaim.proverId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='location', full_name='eu.surething_project.core.LocationClaim.location', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='eu.surething_project.core.LocationClaim.time', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='evidenceType', full_name='eu.surething_project.core.LocationClaim.evidenceType', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='evidence', full_name='eu.surething_project.core.LocationClaim.evidence', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=321,
)


_SIGNEDLOCATIONCLAIM = _descriptor.Descriptor(
  name='SignedLocationClaim',
  full_name='eu.surething_project.core.SignedLocationClaim',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='claim', full_name='eu.surething_project.core.SignedLocationClaim.claim', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='proverSignature', full_name='eu.surething_project.core.SignedLocationClaim.proverSignature', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=465,
)

_LOCATIONCLAIM.fields_by_name['location'].message_type = loc__time__pb2._LOCATION
_LOCATIONCLAIM.fields_by_name['time'].message_type = loc__time__pb2._TIME
_LOCATIONCLAIM.fields_by_name['evidence'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_SIGNEDLOCATIONCLAIM.fields_by_name['claim'].message_type = _LOCATIONCLAIM
_SIGNEDLOCATIONCLAIM.fields_by_name['proverSignature'].message_type = signature__pb2._SIGNATURE
DESCRIPTOR.message_types_by_name['LocationClaim'] = _LOCATIONCLAIM
DESCRIPTOR.message_types_by_name['SignedLocationClaim'] = _SIGNEDLOCATIONCLAIM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LocationClaim = _reflection.GeneratedProtocolMessageType('LocationClaim', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONCLAIM,
  '__module__' : 'loc_claim_pb2'
  # @@protoc_insertion_point(class_scope:eu.surething_project.core.LocationClaim)
  })
_sym_db.RegisterMessage(LocationClaim)

SignedLocationClaim = _reflection.GeneratedProtocolMessageType('SignedLocationClaim', (_message.Message,), {
  'DESCRIPTOR' : _SIGNEDLOCATIONCLAIM,
  '__module__' : 'loc_claim_pb2'
  # @@protoc_insertion_point(class_scope:eu.surething_project.core.SignedLocationClaim)
  })
_sym_db.RegisterMessage(SignedLocationClaim)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
