# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: location-proof.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='location-proof.proto',
  package='pt.ulisboa.tecnico.surethingcore',
  syntax='proto3',
  serialized_options=b'\n.pt.ulisboa.tecnico.surethingcore.locationproofB\036SureThingLocationProofEntitiesP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14location-proof.proto\x12 pt.ulisboa.tecnico.surethingcore\"\x80\x01\n\x12LocationProofProto\x12\x13\n\x0bgeolocation\x18\x02 \x01(\t\x12\x10\n\x08proverId\x18\x03 \x01(\x03\x12\x12\n\nverifierId\x18\x04 \x01(\x03\x12\n\n\x02\x63\x61\x18\x05 \x01(\x03\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\x12\x10\n\x08\x65vidence\x18\x07 \x01(\t\"{\n\x18SignedLocationProofProto\x12\n\n\x02id\x18\x01 \x01(\x03\x12@\n\x02lp\x18\x02 \x01(\x0b\x32\x34.pt.ulisboa.tecnico.surethingcore.LocationProofProto\x12\x11\n\tsignature\x18\x03 \x01(\x0c\"n\n\x13LocationProofsProto\x12W\n\x13locationProofsProto\x18\x01 \x03(\x0b\x32:.pt.ulisboa.tecnico.surethingcore.SignedLocationProofProtoBR\n.pt.ulisboa.tecnico.surethingcore.locationproofB\x1eSureThingLocationProofEntitiesP\x01\x62\x06proto3'
)




_LOCATIONPROOFPROTO = _descriptor.Descriptor(
  name='LocationProofProto',
  full_name='pt.ulisboa.tecnico.surethingcore.LocationProofProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='geolocation', full_name='pt.ulisboa.tecnico.surethingcore.LocationProofProto.geolocation', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='proverId', full_name='pt.ulisboa.tecnico.surethingcore.LocationProofProto.proverId', index=1,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='verifierId', full_name='pt.ulisboa.tecnico.surethingcore.LocationProofProto.verifierId', index=2,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ca', full_name='pt.ulisboa.tecnico.surethingcore.LocationProofProto.ca', index=3,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='pt.ulisboa.tecnico.surethingcore.LocationProofProto.timestamp', index=4,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='evidence', full_name='pt.ulisboa.tecnico.surethingcore.LocationProofProto.evidence', index=5,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=187,
)


_SIGNEDLOCATIONPROOFPROTO = _descriptor.Descriptor(
  name='SignedLocationProofProto',
  full_name='pt.ulisboa.tecnico.surethingcore.SignedLocationProofProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='pt.ulisboa.tecnico.surethingcore.SignedLocationProofProto.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lp', full_name='pt.ulisboa.tecnico.surethingcore.SignedLocationProofProto.lp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signature', full_name='pt.ulisboa.tecnico.surethingcore.SignedLocationProofProto.signature', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=312,
)


_LOCATIONPROOFSPROTO = _descriptor.Descriptor(
  name='LocationProofsProto',
  full_name='pt.ulisboa.tecnico.surethingcore.LocationProofsProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='locationProofsProto', full_name='pt.ulisboa.tecnico.surethingcore.LocationProofsProto.locationProofsProto', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=424,
)

_SIGNEDLOCATIONPROOFPROTO.fields_by_name['lp'].message_type = _LOCATIONPROOFPROTO
_LOCATIONPROOFSPROTO.fields_by_name['locationProofsProto'].message_type = _SIGNEDLOCATIONPROOFPROTO
DESCRIPTOR.message_types_by_name['LocationProofProto'] = _LOCATIONPROOFPROTO
DESCRIPTOR.message_types_by_name['SignedLocationProofProto'] = _SIGNEDLOCATIONPROOFPROTO
DESCRIPTOR.message_types_by_name['LocationProofsProto'] = _LOCATIONPROOFSPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LocationProofProto = _reflection.GeneratedProtocolMessageType('LocationProofProto', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONPROOFPROTO,
  '__module__' : 'location_proof_pb2'
  # @@protoc_insertion_point(class_scope:pt.ulisboa.tecnico.surethingcore.LocationProofProto)
  })
_sym_db.RegisterMessage(LocationProofProto)

SignedLocationProofProto = _reflection.GeneratedProtocolMessageType('SignedLocationProofProto', (_message.Message,), {
  'DESCRIPTOR' : _SIGNEDLOCATIONPROOFPROTO,
  '__module__' : 'location_proof_pb2'
  # @@protoc_insertion_point(class_scope:pt.ulisboa.tecnico.surethingcore.SignedLocationProofProto)
  })
_sym_db.RegisterMessage(SignedLocationProofProto)

LocationProofsProto = _reflection.GeneratedProtocolMessageType('LocationProofsProto', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONPROOFSPROTO,
  '__module__' : 'location_proof_pb2'
  # @@protoc_insertion_point(class_scope:pt.ulisboa.tecnico.surethingcore.LocationProofsProto)
  })
_sym_db.RegisterMessage(LocationProofsProto)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
