// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loc_proof.proto

package eu.surething_project.core.grpc.comm;

public final class LocProofProto {
  private LocProofProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_surething_project_core_grpc_LocationProof_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eu_surething_project_core_grpc_LocationProof_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_surething_project_core_grpc_SignedLocationProof_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eu_surething_project_core_grpc_SignedLocationProof_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017loc_proof.proto\022\036eu.surething_project." +
      "core.grpc\032\031google/protobuf/any.proto\032\016lo" +
      "c_time.proto\032\017signature.proto\"\241\001\n\rLocati" +
      "onProof\022\022\n\nverifierId\030\001 \001(\t\022\017\n\007claimId\030\002" +
      " \001(\t\022-\n\004time\030\004 \001(\0132\037.eu.surething_projec" +
      "t.core.Time\022\024\n\014evidenceType\030\005 \001(\t\022&\n\010evi" +
      "dence\030\006 \001(\0132\024.google.protobuf.Any\"\240\001\n\023Si" +
      "gnedLocationProof\022C\n\014verification\030\001 \001(\0132" +
      "-.eu.surething_project.core.grpc.Locatio" +
      "nProof\022D\n\021verifierSignature\030\002 \001(\0132).eu.s" +
      "urething_project.core.grpc.SignatureB6\n#" +
      "eu.surething_project.core.grpc.commB\rLoc" +
      "ProofProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          eu.surething_project.core.grpc.LocTimeProto.getDescriptor(),
          eu.surething_project.core.grpc.signature.SignatureProto.getDescriptor(),
        }, assigner);
    internal_static_eu_surething_project_core_grpc_LocationProof_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_eu_surething_project_core_grpc_LocationProof_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eu_surething_project_core_grpc_LocationProof_descriptor,
        new java.lang.String[] { "VerifierId", "ClaimId", "Time", "EvidenceType", "Evidence", });
    internal_static_eu_surething_project_core_grpc_SignedLocationProof_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_eu_surething_project_core_grpc_SignedLocationProof_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eu_surething_project_core_grpc_SignedLocationProof_descriptor,
        new java.lang.String[] { "Verification", "VerifierSignature", });
    com.google.protobuf.AnyProto.getDescriptor();
    eu.surething_project.core.grpc.LocTimeProto.getDescriptor();
    eu.surething_project.core.grpc.signature.SignatureProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
