// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loc_claim.proto

package eu.surething_project.core.grpc.comm;

public interface SignedLocationClaimOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eu.surething_project.core.grpc.SignedLocationClaim)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * claim
   * </pre>
   *
   * <code>.eu.surething_project.core.grpc.LocationClaim claim = 1;</code>
   */
  boolean hasClaim();
  /**
   * <pre>
   * claim
   * </pre>
   *
   * <code>.eu.surething_project.core.grpc.LocationClaim claim = 1;</code>
   */
  eu.surething_project.core.grpc.comm.LocationClaim getClaim();
  /**
   * <pre>
   * claim
   * </pre>
   *
   * <code>.eu.surething_project.core.grpc.LocationClaim claim = 1;</code>
   */
  eu.surething_project.core.grpc.comm.LocationClaimOrBuilder getClaimOrBuilder();

  /**
   * <pre>
   * prover's signature
   * </pre>
   *
   * <code>.eu.surething_project.core.grpc.Signature proverSignature = 2;</code>
   */
  boolean hasProverSignature();
  /**
   * <pre>
   * prover's signature
   * </pre>
   *
   * <code>.eu.surething_project.core.grpc.Signature proverSignature = 2;</code>
   */
  eu.surething_project.core.grpc.signature.Signature getProverSignature();
  /**
   * <pre>
   * prover's signature
   * </pre>
   *
   * <code>.eu.surething_project.core.grpc.Signature proverSignature = 2;</code>
   */
  eu.surething_project.core.grpc.signature.SignatureOrBuilder getProverSignatureOrBuilder();
}
