// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loc_endorse.proto

package eu.surething_project.core.grpc;

/**
 * <pre>
 * Location Endorsement generated by the witness to testify a prover's location claim(s)
 * </pre>
 *
 * Protobuf type {@code eu.surething_project.core.LocationEndorsement}
 */
public  final class LocationEndorsement extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:eu.surething_project.core.LocationEndorsement)
    LocationEndorsementOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LocationEndorsement.newBuilder() to construct.
  private LocationEndorsement(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LocationEndorsement() {
    witnessId_ = "";
    claimId_ = "";
    evidenceType_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LocationEndorsement(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            witnessId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            claimId_ = s;
            break;
          }
          case 26: {
            eu.surething_project.core.grpc.Time.Builder subBuilder = null;
            if (time_ != null) {
              subBuilder = time_.toBuilder();
            }
            time_ = input.readMessage(eu.surething_project.core.grpc.Time.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(time_);
              time_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            evidenceType_ = s;
            break;
          }
          case 42: {
            com.google.protobuf.Any.Builder subBuilder = null;
            if (evidence_ != null) {
              subBuilder = evidence_.toBuilder();
            }
            evidence_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(evidence_);
              evidence_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return eu.surething_project.core.grpc.LocEndorseProto.internal_static_eu_surething_project_core_LocationEndorsement_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return eu.surething_project.core.grpc.LocEndorseProto.internal_static_eu_surething_project_core_LocationEndorsement_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            eu.surething_project.core.grpc.LocationEndorsement.class, eu.surething_project.core.grpc.LocationEndorsement.Builder.class);
  }

  public static final int WITNESSID_FIELD_NUMBER = 1;
  private volatile java.lang.Object witnessId_;
  /**
   * <pre>
   * witness unique id
   * </pre>
   *
   * <code>string witnessId = 1;</code>
   */
  public java.lang.String getWitnessId() {
    java.lang.Object ref = witnessId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      witnessId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * witness unique id
   * </pre>
   *
   * <code>string witnessId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getWitnessIdBytes() {
    java.lang.Object ref = witnessId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      witnessId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLAIMID_FIELD_NUMBER = 2;
  private volatile java.lang.Object claimId_;
  /**
   * <pre>
   * the original location claim of the prover
   * </pre>
   *
   * <code>string claimId = 2;</code>
   */
  public java.lang.String getClaimId() {
    java.lang.Object ref = claimId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      claimId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * the original location claim of the prover
   * </pre>
   *
   * <code>string claimId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getClaimIdBytes() {
    java.lang.Object ref = claimId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      claimId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIME_FIELD_NUMBER = 3;
  private eu.surething_project.core.grpc.Time time_;
  /**
   * <pre>
   * time of location endorsement - in one of alternative time schemas
   * </pre>
   *
   * <code>.eu.surething_project.core.Time time = 3;</code>
   */
  public boolean hasTime() {
    return time_ != null;
  }
  /**
   * <pre>
   * time of location endorsement - in one of alternative time schemas
   * </pre>
   *
   * <code>.eu.surething_project.core.Time time = 3;</code>
   */
  public eu.surething_project.core.grpc.Time getTime() {
    return time_ == null ? eu.surething_project.core.grpc.Time.getDefaultInstance() : time_;
  }
  /**
   * <pre>
   * time of location endorsement - in one of alternative time schemas
   * </pre>
   *
   * <code>.eu.surething_project.core.Time time = 3;</code>
   */
  public eu.surething_project.core.grpc.TimeOrBuilder getTimeOrBuilder() {
    return getTime();
  }

  public static final int EVIDENCETYPE_FIELD_NUMBER = 4;
  private volatile java.lang.Object evidenceType_;
  /**
   * <pre>
   * type of the evidence
   * </pre>
   *
   * <code>string evidenceType = 4;</code>
   */
  public java.lang.String getEvidenceType() {
    java.lang.Object ref = evidenceType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      evidenceType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * type of the evidence
   * </pre>
   *
   * <code>string evidenceType = 4;</code>
   */
  public com.google.protobuf.ByteString
      getEvidenceTypeBytes() {
    java.lang.Object ref = evidenceType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      evidenceType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVIDENCE_FIELD_NUMBER = 5;
  private com.google.protobuf.Any evidence_;
  /**
   * <pre>
   * endorsement evidence
   * </pre>
   *
   * <code>.google.protobuf.Any evidence = 5;</code>
   */
  public boolean hasEvidence() {
    return evidence_ != null;
  }
  /**
   * <pre>
   * endorsement evidence
   * </pre>
   *
   * <code>.google.protobuf.Any evidence = 5;</code>
   */
  public com.google.protobuf.Any getEvidence() {
    return evidence_ == null ? com.google.protobuf.Any.getDefaultInstance() : evidence_;
  }
  /**
   * <pre>
   * endorsement evidence
   * </pre>
   *
   * <code>.google.protobuf.Any evidence = 5;</code>
   */
  public com.google.protobuf.AnyOrBuilder getEvidenceOrBuilder() {
    return getEvidence();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getWitnessIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, witnessId_);
    }
    if (!getClaimIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, claimId_);
    }
    if (time_ != null) {
      output.writeMessage(3, getTime());
    }
    if (!getEvidenceTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, evidenceType_);
    }
    if (evidence_ != null) {
      output.writeMessage(5, getEvidence());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getWitnessIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, witnessId_);
    }
    if (!getClaimIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, claimId_);
    }
    if (time_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getTime());
    }
    if (!getEvidenceTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, evidenceType_);
    }
    if (evidence_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getEvidence());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof eu.surething_project.core.grpc.LocationEndorsement)) {
      return super.equals(obj);
    }
    eu.surething_project.core.grpc.LocationEndorsement other = (eu.surething_project.core.grpc.LocationEndorsement) obj;

    boolean result = true;
    result = result && getWitnessId()
        .equals(other.getWitnessId());
    result = result && getClaimId()
        .equals(other.getClaimId());
    result = result && (hasTime() == other.hasTime());
    if (hasTime()) {
      result = result && getTime()
          .equals(other.getTime());
    }
    result = result && getEvidenceType()
        .equals(other.getEvidenceType());
    result = result && (hasEvidence() == other.hasEvidence());
    if (hasEvidence()) {
      result = result && getEvidence()
          .equals(other.getEvidence());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WITNESSID_FIELD_NUMBER;
    hash = (53 * hash) + getWitnessId().hashCode();
    hash = (37 * hash) + CLAIMID_FIELD_NUMBER;
    hash = (53 * hash) + getClaimId().hashCode();
    if (hasTime()) {
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTime().hashCode();
    }
    hash = (37 * hash) + EVIDENCETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getEvidenceType().hashCode();
    if (hasEvidence()) {
      hash = (37 * hash) + EVIDENCE_FIELD_NUMBER;
      hash = (53 * hash) + getEvidence().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static eu.surething_project.core.grpc.LocationEndorsement parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.surething_project.core.grpc.LocationEndorsement parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.LocationEndorsement parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.surething_project.core.grpc.LocationEndorsement parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.LocationEndorsement parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.surething_project.core.grpc.LocationEndorsement parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.LocationEndorsement parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.surething_project.core.grpc.LocationEndorsement parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.LocationEndorsement parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static eu.surething_project.core.grpc.LocationEndorsement parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.surething_project.core.grpc.LocationEndorsement parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.surething_project.core.grpc.LocationEndorsement parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(eu.surething_project.core.grpc.LocationEndorsement prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Location Endorsement generated by the witness to testify a prover's location claim(s)
   * </pre>
   *
   * Protobuf type {@code eu.surething_project.core.LocationEndorsement}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:eu.surething_project.core.LocationEndorsement)
      eu.surething_project.core.grpc.LocationEndorsementOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.surething_project.core.grpc.LocEndorseProto.internal_static_eu_surething_project_core_LocationEndorsement_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.surething_project.core.grpc.LocEndorseProto.internal_static_eu_surething_project_core_LocationEndorsement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.surething_project.core.grpc.LocationEndorsement.class, eu.surething_project.core.grpc.LocationEndorsement.Builder.class);
    }

    // Construct using eu.surething_project.core.grpc.LocationEndorsement.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      witnessId_ = "";

      claimId_ = "";

      if (timeBuilder_ == null) {
        time_ = null;
      } else {
        time_ = null;
        timeBuilder_ = null;
      }
      evidenceType_ = "";

      if (evidenceBuilder_ == null) {
        evidence_ = null;
      } else {
        evidence_ = null;
        evidenceBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return eu.surething_project.core.grpc.LocEndorseProto.internal_static_eu_surething_project_core_LocationEndorsement_descriptor;
    }

    @java.lang.Override
    public eu.surething_project.core.grpc.LocationEndorsement getDefaultInstanceForType() {
      return eu.surething_project.core.grpc.LocationEndorsement.getDefaultInstance();
    }

    @java.lang.Override
    public eu.surething_project.core.grpc.LocationEndorsement build() {
      eu.surething_project.core.grpc.LocationEndorsement result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public eu.surething_project.core.grpc.LocationEndorsement buildPartial() {
      eu.surething_project.core.grpc.LocationEndorsement result = new eu.surething_project.core.grpc.LocationEndorsement(this);
      result.witnessId_ = witnessId_;
      result.claimId_ = claimId_;
      if (timeBuilder_ == null) {
        result.time_ = time_;
      } else {
        result.time_ = timeBuilder_.build();
      }
      result.evidenceType_ = evidenceType_;
      if (evidenceBuilder_ == null) {
        result.evidence_ = evidence_;
      } else {
        result.evidence_ = evidenceBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof eu.surething_project.core.grpc.LocationEndorsement) {
        return mergeFrom((eu.surething_project.core.grpc.LocationEndorsement)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(eu.surething_project.core.grpc.LocationEndorsement other) {
      if (other == eu.surething_project.core.grpc.LocationEndorsement.getDefaultInstance()) return this;
      if (!other.getWitnessId().isEmpty()) {
        witnessId_ = other.witnessId_;
        onChanged();
      }
      if (!other.getClaimId().isEmpty()) {
        claimId_ = other.claimId_;
        onChanged();
      }
      if (other.hasTime()) {
        mergeTime(other.getTime());
      }
      if (!other.getEvidenceType().isEmpty()) {
        evidenceType_ = other.evidenceType_;
        onChanged();
      }
      if (other.hasEvidence()) {
        mergeEvidence(other.getEvidence());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      eu.surething_project.core.grpc.LocationEndorsement parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (eu.surething_project.core.grpc.LocationEndorsement) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object witnessId_ = "";
    /**
     * <pre>
     * witness unique id
     * </pre>
     *
     * <code>string witnessId = 1;</code>
     */
    public java.lang.String getWitnessId() {
      java.lang.Object ref = witnessId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        witnessId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * witness unique id
     * </pre>
     *
     * <code>string witnessId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWitnessIdBytes() {
      java.lang.Object ref = witnessId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        witnessId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * witness unique id
     * </pre>
     *
     * <code>string witnessId = 1;</code>
     */
    public Builder setWitnessId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      witnessId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * witness unique id
     * </pre>
     *
     * <code>string witnessId = 1;</code>
     */
    public Builder clearWitnessId() {
      
      witnessId_ = getDefaultInstance().getWitnessId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * witness unique id
     * </pre>
     *
     * <code>string witnessId = 1;</code>
     */
    public Builder setWitnessIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      witnessId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object claimId_ = "";
    /**
     * <pre>
     * the original location claim of the prover
     * </pre>
     *
     * <code>string claimId = 2;</code>
     */
    public java.lang.String getClaimId() {
      java.lang.Object ref = claimId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        claimId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * the original location claim of the prover
     * </pre>
     *
     * <code>string claimId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClaimIdBytes() {
      java.lang.Object ref = claimId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        claimId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * the original location claim of the prover
     * </pre>
     *
     * <code>string claimId = 2;</code>
     */
    public Builder setClaimId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      claimId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the original location claim of the prover
     * </pre>
     *
     * <code>string claimId = 2;</code>
     */
    public Builder clearClaimId() {
      
      claimId_ = getDefaultInstance().getClaimId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the original location claim of the prover
     * </pre>
     *
     * <code>string claimId = 2;</code>
     */
    public Builder setClaimIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      claimId_ = value;
      onChanged();
      return this;
    }

    private eu.surething_project.core.grpc.Time time_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        eu.surething_project.core.grpc.Time, eu.surething_project.core.grpc.Time.Builder, eu.surething_project.core.grpc.TimeOrBuilder> timeBuilder_;
    /**
     * <pre>
     * time of location endorsement - in one of alternative time schemas
     * </pre>
     *
     * <code>.eu.surething_project.core.Time time = 3;</code>
     */
    public boolean hasTime() {
      return timeBuilder_ != null || time_ != null;
    }
    /**
     * <pre>
     * time of location endorsement - in one of alternative time schemas
     * </pre>
     *
     * <code>.eu.surething_project.core.Time time = 3;</code>
     */
    public eu.surething_project.core.grpc.Time getTime() {
      if (timeBuilder_ == null) {
        return time_ == null ? eu.surething_project.core.grpc.Time.getDefaultInstance() : time_;
      } else {
        return timeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * time of location endorsement - in one of alternative time schemas
     * </pre>
     *
     * <code>.eu.surething_project.core.Time time = 3;</code>
     */
    public Builder setTime(eu.surething_project.core.grpc.Time value) {
      if (timeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        time_ = value;
        onChanged();
      } else {
        timeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * time of location endorsement - in one of alternative time schemas
     * </pre>
     *
     * <code>.eu.surething_project.core.Time time = 3;</code>
     */
    public Builder setTime(
        eu.surething_project.core.grpc.Time.Builder builderForValue) {
      if (timeBuilder_ == null) {
        time_ = builderForValue.build();
        onChanged();
      } else {
        timeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * time of location endorsement - in one of alternative time schemas
     * </pre>
     *
     * <code>.eu.surething_project.core.Time time = 3;</code>
     */
    public Builder mergeTime(eu.surething_project.core.grpc.Time value) {
      if (timeBuilder_ == null) {
        if (time_ != null) {
          time_ =
            eu.surething_project.core.grpc.Time.newBuilder(time_).mergeFrom(value).buildPartial();
        } else {
          time_ = value;
        }
        onChanged();
      } else {
        timeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * time of location endorsement - in one of alternative time schemas
     * </pre>
     *
     * <code>.eu.surething_project.core.Time time = 3;</code>
     */
    public Builder clearTime() {
      if (timeBuilder_ == null) {
        time_ = null;
        onChanged();
      } else {
        time_ = null;
        timeBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * time of location endorsement - in one of alternative time schemas
     * </pre>
     *
     * <code>.eu.surething_project.core.Time time = 3;</code>
     */
    public eu.surething_project.core.grpc.Time.Builder getTimeBuilder() {
      
      onChanged();
      return getTimeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * time of location endorsement - in one of alternative time schemas
     * </pre>
     *
     * <code>.eu.surething_project.core.Time time = 3;</code>
     */
    public eu.surething_project.core.grpc.TimeOrBuilder getTimeOrBuilder() {
      if (timeBuilder_ != null) {
        return timeBuilder_.getMessageOrBuilder();
      } else {
        return time_ == null ?
            eu.surething_project.core.grpc.Time.getDefaultInstance() : time_;
      }
    }
    /**
     * <pre>
     * time of location endorsement - in one of alternative time schemas
     * </pre>
     *
     * <code>.eu.surething_project.core.Time time = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        eu.surething_project.core.grpc.Time, eu.surething_project.core.grpc.Time.Builder, eu.surething_project.core.grpc.TimeOrBuilder> 
        getTimeFieldBuilder() {
      if (timeBuilder_ == null) {
        timeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            eu.surething_project.core.grpc.Time, eu.surething_project.core.grpc.Time.Builder, eu.surething_project.core.grpc.TimeOrBuilder>(
                getTime(),
                getParentForChildren(),
                isClean());
        time_ = null;
      }
      return timeBuilder_;
    }

    private java.lang.Object evidenceType_ = "";
    /**
     * <pre>
     * type of the evidence
     * </pre>
     *
     * <code>string evidenceType = 4;</code>
     */
    public java.lang.String getEvidenceType() {
      java.lang.Object ref = evidenceType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        evidenceType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * type of the evidence
     * </pre>
     *
     * <code>string evidenceType = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEvidenceTypeBytes() {
      java.lang.Object ref = evidenceType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        evidenceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * type of the evidence
     * </pre>
     *
     * <code>string evidenceType = 4;</code>
     */
    public Builder setEvidenceType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      evidenceType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * type of the evidence
     * </pre>
     *
     * <code>string evidenceType = 4;</code>
     */
    public Builder clearEvidenceType() {
      
      evidenceType_ = getDefaultInstance().getEvidenceType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * type of the evidence
     * </pre>
     *
     * <code>string evidenceType = 4;</code>
     */
    public Builder setEvidenceTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      evidenceType_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Any evidence_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> evidenceBuilder_;
    /**
     * <pre>
     * endorsement evidence
     * </pre>
     *
     * <code>.google.protobuf.Any evidence = 5;</code>
     */
    public boolean hasEvidence() {
      return evidenceBuilder_ != null || evidence_ != null;
    }
    /**
     * <pre>
     * endorsement evidence
     * </pre>
     *
     * <code>.google.protobuf.Any evidence = 5;</code>
     */
    public com.google.protobuf.Any getEvidence() {
      if (evidenceBuilder_ == null) {
        return evidence_ == null ? com.google.protobuf.Any.getDefaultInstance() : evidence_;
      } else {
        return evidenceBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * endorsement evidence
     * </pre>
     *
     * <code>.google.protobuf.Any evidence = 5;</code>
     */
    public Builder setEvidence(com.google.protobuf.Any value) {
      if (evidenceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        evidence_ = value;
        onChanged();
      } else {
        evidenceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * endorsement evidence
     * </pre>
     *
     * <code>.google.protobuf.Any evidence = 5;</code>
     */
    public Builder setEvidence(
        com.google.protobuf.Any.Builder builderForValue) {
      if (evidenceBuilder_ == null) {
        evidence_ = builderForValue.build();
        onChanged();
      } else {
        evidenceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * endorsement evidence
     * </pre>
     *
     * <code>.google.protobuf.Any evidence = 5;</code>
     */
    public Builder mergeEvidence(com.google.protobuf.Any value) {
      if (evidenceBuilder_ == null) {
        if (evidence_ != null) {
          evidence_ =
            com.google.protobuf.Any.newBuilder(evidence_).mergeFrom(value).buildPartial();
        } else {
          evidence_ = value;
        }
        onChanged();
      } else {
        evidenceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * endorsement evidence
     * </pre>
     *
     * <code>.google.protobuf.Any evidence = 5;</code>
     */
    public Builder clearEvidence() {
      if (evidenceBuilder_ == null) {
        evidence_ = null;
        onChanged();
      } else {
        evidence_ = null;
        evidenceBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * endorsement evidence
     * </pre>
     *
     * <code>.google.protobuf.Any evidence = 5;</code>
     */
    public com.google.protobuf.Any.Builder getEvidenceBuilder() {
      
      onChanged();
      return getEvidenceFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * endorsement evidence
     * </pre>
     *
     * <code>.google.protobuf.Any evidence = 5;</code>
     */
    public com.google.protobuf.AnyOrBuilder getEvidenceOrBuilder() {
      if (evidenceBuilder_ != null) {
        return evidenceBuilder_.getMessageOrBuilder();
      } else {
        return evidence_ == null ?
            com.google.protobuf.Any.getDefaultInstance() : evidence_;
      }
    }
    /**
     * <pre>
     * endorsement evidence
     * </pre>
     *
     * <code>.google.protobuf.Any evidence = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
        getEvidenceFieldBuilder() {
      if (evidenceBuilder_ == null) {
        evidenceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                getEvidence(),
                getParentForChildren(),
                isClean());
        evidence_ = null;
      }
      return evidenceBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:eu.surething_project.core.LocationEndorsement)
  }

  // @@protoc_insertion_point(class_scope:eu.surething_project.core.LocationEndorsement)
  private static final eu.surething_project.core.grpc.LocationEndorsement DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new eu.surething_project.core.grpc.LocationEndorsement();
  }

  public static eu.surething_project.core.grpc.LocationEndorsement getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LocationEndorsement>
      PARSER = new com.google.protobuf.AbstractParser<LocationEndorsement>() {
    @java.lang.Override
    public LocationEndorsement parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LocationEndorsement(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LocationEndorsement> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LocationEndorsement> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public eu.surething_project.core.grpc.LocationEndorsement getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

