// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loc_endorse.proto

package eu.surething_project.core.grpc;

public interface SignedLocationEndorsementOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eu.surething_project.core.SignedLocationEndorsement)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.eu.surething_project.core.LocationEndorsement endorsement = 1;</code>
   */
  boolean hasEndorsement();
  /**
   * <code>.eu.surething_project.core.LocationEndorsement endorsement = 1;</code>
   */
  eu.surething_project.core.grpc.LocationEndorsement getEndorsement();
  /**
   * <code>.eu.surething_project.core.LocationEndorsement endorsement = 1;</code>
   */
  eu.surething_project.core.grpc.LocationEndorsementOrBuilder getEndorsementOrBuilder();

  /**
   * <code>.eu.surething_project.core.Signature witnessSignature = 2;</code>
   */
  boolean hasWitnessSignature();
  /**
   * <code>.eu.surething_project.core.Signature witnessSignature = 2;</code>
   */
  eu.surething_project.core.grpc.Signature getWitnessSignature();
  /**
   * <code>.eu.surething_project.core.Signature witnessSignature = 2;</code>
   */
  eu.surething_project.core.grpc.SignatureOrBuilder getWitnessSignatureOrBuilder();
}
