// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loc_time.proto

package eu.surething_project.core.grpc;

public interface TimeIntervalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eu.surething_project.core.TimeInterval)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Timestamp begin = 1;</code>
   */
  boolean hasBegin();
  /**
   * <code>.google.protobuf.Timestamp begin = 1;</code>
   */
  com.google.protobuf.Timestamp getBegin();
  /**
   * <code>.google.protobuf.Timestamp begin = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getBeginOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp end = 2;</code>
   */
  boolean hasEnd();
  /**
   * <code>.google.protobuf.Timestamp end = 2;</code>
   */
  com.google.protobuf.Timestamp getEnd();
  /**
   * <code>.google.protobuf.Timestamp end = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getEndOrBuilder();
}
