// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loc_time.proto

package eu.surething_project.core.grpc;

public interface TimeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eu.surething_project.core.Time)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * timestamp
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 1;</code>
   */
  boolean hasTimestamp();
  /**
   * <pre>
   * timestamp
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 1;</code>
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <pre>
   * timestamp
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

  /**
   * <pre>
   * interval defined by two timestamps
   * </pre>
   *
   * <code>.eu.surething_project.core.TimeInterval interval = 2;</code>
   */
  boolean hasInterval();
  /**
   * <pre>
   * interval defined by two timestamps
   * </pre>
   *
   * <code>.eu.surething_project.core.TimeInterval interval = 2;</code>
   */
  eu.surething_project.core.grpc.TimeInterval getInterval();
  /**
   * <pre>
   * interval defined by two timestamps
   * </pre>
   *
   * <code>.eu.surething_project.core.TimeInterval interval = 2;</code>
   */
  eu.surething_project.core.grpc.TimeIntervalOrBuilder getIntervalOrBuilder();

  /**
   * <pre>
   * time relative to epoch
   * </pre>
   *
   * <code>.eu.surething_project.core.EpochTime relativeToEpoch = 3;</code>
   */
  boolean hasRelativeToEpoch();
  /**
   * <pre>
   * time relative to epoch
   * </pre>
   *
   * <code>.eu.surething_project.core.EpochTime relativeToEpoch = 3;</code>
   */
  eu.surething_project.core.grpc.EpochTime getRelativeToEpoch();
  /**
   * <pre>
   * time relative to epoch
   * </pre>
   *
   * <code>.eu.surething_project.core.EpochTime relativeToEpoch = 3;</code>
   */
  eu.surething_project.core.grpc.EpochTimeOrBuilder getRelativeToEpochOrBuilder();

  /**
   * <pre>
   * use when we do no have time information
   * </pre>
   *
   * <code>.google.protobuf.Empty empty = 4;</code>
   */
  boolean hasEmpty();
  /**
   * <pre>
   * use when we do no have time information
   * </pre>
   *
   * <code>.google.protobuf.Empty empty = 4;</code>
   */
  com.google.protobuf.Empty getEmpty();
  /**
   * <pre>
   * use when we do no have time information
   * </pre>
   *
   * <code>.google.protobuf.Empty empty = 4;</code>
   */
  com.google.protobuf.EmptyOrBuilder getEmptyOrBuilder();

  public eu.surething_project.core.grpc.Time.TimeCase getTimeCase();
}
