# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: locationclaim.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='locationclaim.proto',
  package='pt.ulisboa.tecnico.surethingcore',
  syntax='proto3',
  serialized_options=b'\n.pt.ulisboa.tecnico.surethingcore.locationclaimB\036SureThingLocationClaimEntitiesP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13locationclaim.proto\x12 pt.ulisboa.tecnico.surethingcore\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"\xe8\x01\n\rLocationClaim\x12\x10\n\x08proverId\x18\x01 \x01(\x03\x12\x10\n\x08location\x18\x02 \x01(\t\x12\x44\n\x0c\x65videnceType\x18\x03 \x01(\x0e\x32..pt.ulisboa.tecnico.surethingcore.EvidenceType\x12+\n\rclaimEvidence\x18\x04 \x03(\x0b\x32\x14.google.protobuf.Any\x12-\n\ttimestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tsignature\x18\x06 \x01(\x0c*O\n\x0c\x45videnceType\x12\x08\n\x04WIFI\x10\x00\x12\x07\n\x03GPS\x10\x01\x12\r\n\tBLUETOOTH\x10\x02\x12\n\n\x06\x42\x45\x41\x43ON\x10\x03\x12\x11\n\rAMBIENTSENSOR\x10\x04\x42R\n.pt.ulisboa.tecnico.surethingcore.locationclaimB\x1eSureThingLocationClaimEntitiesP\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])

_EVIDENCETYPE = _descriptor.EnumDescriptor(
  name='EvidenceType',
  full_name='pt.ulisboa.tecnico.surethingcore.EvidenceType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WIFI', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GPS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BLUETOOTH', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BEACON', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AMBIENTSENSOR', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=352,
  serialized_end=431,
)
_sym_db.RegisterEnumDescriptor(_EVIDENCETYPE)

EvidenceType = enum_type_wrapper.EnumTypeWrapper(_EVIDENCETYPE)
WIFI = 0
GPS = 1
BLUETOOTH = 2
BEACON = 3
AMBIENTSENSOR = 4



_LOCATIONCLAIM = _descriptor.Descriptor(
  name='LocationClaim',
  full_name='pt.ulisboa.tecnico.surethingcore.LocationClaim',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='proverId', full_name='pt.ulisboa.tecnico.surethingcore.LocationClaim.proverId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='location', full_name='pt.ulisboa.tecnico.surethingcore.LocationClaim.location', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='evidenceType', full_name='pt.ulisboa.tecnico.surethingcore.LocationClaim.evidenceType', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='claimEvidence', full_name='pt.ulisboa.tecnico.surethingcore.LocationClaim.claimEvidence', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='pt.ulisboa.tecnico.surethingcore.LocationClaim.timestamp', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signature', full_name='pt.ulisboa.tecnico.surethingcore.LocationClaim.signature', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=350,
)

_LOCATIONCLAIM.fields_by_name['evidenceType'].enum_type = _EVIDENCETYPE
_LOCATIONCLAIM.fields_by_name['claimEvidence'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_LOCATIONCLAIM.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['LocationClaim'] = _LOCATIONCLAIM
DESCRIPTOR.enum_types_by_name['EvidenceType'] = _EVIDENCETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LocationClaim = _reflection.GeneratedProtocolMessageType('LocationClaim', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONCLAIM,
  '__module__' : 'locationclaim_pb2'
  # @@protoc_insertion_point(class_scope:pt.ulisboa.tecnico.surethingcore.LocationClaim)
  })
_sym_db.RegisterMessage(LocationClaim)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
